run:
  timeout: 5m
  build-tags:
    - integration
  skip-dirs:
    - "testdata"
  skip-files:
    - pkg/file/file_windows.go
linters:
  enable:
    - bodyclose
    - gochecknoinits
    - gochecknoglobals
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - goimports
    - gosec
    - misspell
    - nestif
    - revive
    - testpackage
    - unconvert
    - usestdlibvars
    - whitespace
    - wsl
linters-settings:
  revive:
    rules:
      - name: bare-return
      - name: blank-imports
      - name: duplicated-imports
      - name: defer
      - name: dot-imports
      - name: early-return
      - name: errorf
      - name: error-naming
      - name: error-return
      - name: error-strings
      - name: exported
      - name: function-result-limit
        arguments: [3]
      - name: if-return
      - name: increment-decrement
      - name: indent-error-flow
      - name: line-length-limit
        arguments: [125]
      - name: superfluous-else
      - name: range
      - name: receiver-naming
      - name: struct-tag
      - name: time-naming
      - name: unexported-naming
      - name: unexported-return
      - name: unnecessary-stmt
      - name: unused-parameter
      - name: unused-receiver
      - name: var-declaration
      - name: var-naming
issues:
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
  include:
    - EXC0002
