env:
  - GO111MODULE=on
  - GOPROXY=https://goproxy.io
before:
  hooks:
    - go mod download
builds:
- id: wakatime-cli-darwin-amd64
  ldflags:  >-
    -s -w -X github.com/wakatime/wakatime-cli/pkg/version.BuildDate={{ .Date }}
    -X github.com/wakatime/wakatime-cli/pkg/version.Commit={{ .ShortCommit }}
    -X github.com/wakatime/wakatime-cli/pkg/version.Version={{ .Version }}
    -X github.com/wakatime/wakatime-cli/pkg/version.OS=darwin
    -X github.com/wakatime/wakatime-cli/pkg/version.Arch=amd64
  binary: wakatime-cli
  env:
    - CGO_ENABLED=1
    - CC=o64-clang
    - CXX=o64-clang++
  main: ./main.go
  goos:
    - darwin
  goarch:
    - amd64
- id: wakatime-cli-linux-amd64
  ldflags:  >-
    -s -w -X github.com/wakatime/wakatime-cli/pkg/version.BuildDate={{ .Date }}
    -X github.com/wakatime/wakatime-cli/pkg/version.Commit={{ .ShortCommit }}
    -X github.com/wakatime/wakatime-cli/pkg/version.Version={{ .Version }}
    -X github.com/wakatime/wakatime-cli/pkg/version.OS=linux
    -X github.com/wakatime/wakatime-cli/pkg/version.Arch=amd64
  binary: wakatime-cli
  env:
    - CGO_ENABLED=1
  main: ./main.go
  goos:
    - linux
  goarch:
    - amd64
- id: wakatime-cli-windows-amd64
  ldflags:  >-
    -s -w -X github.com/wakatime/wakatime-cli/pkg/version.BuildDate={{ .Date }}
    -X github.com/wakatime/wakatime-cli/pkg/version.Commit={{ .ShortCommit }}
    -X github.com/wakatime/wakatime-cli/pkg/version.Version={{ .Version }}
    -X github.com/wakatime/wakatime-cli/pkg/version.OS=windows
    -X github.com/wakatime/wakatime-cli/pkg/version.Arch=amd64
  binary: wakatime-cli
  env:
    - CGO_ENABLED=1
    - CC=x86_64-w64-mingw32-gcc
    - CXX=x86_64-w64-mingw32-g++
  main: ./main.go
  goos:
    - windows
  goarch:
    - amd64
release:
  prerelease: auto
archives:
  -
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
checksum:
  name_template: 'checksums.txt'
