package main

import (
	"encoding/json"
	"fmt"
	"io/ioutil"
	"os"
	"sort"
	"strings"
	"text/template"

	"github.com/wakatime/wakatime-cli/pkg/heartbeat"
)

const (
	pluginFolder = "pkg/language/plugins"
	outputFile   = "pkg/language/plugins.go"
)

func main() {
	os.Exit(generate())
}

// generate generates go language code for plugin language parsing from templates.
func generate() int {
	files, err := ioutil.ReadDir(pluginFolder)
	if err != nil {
		fmt.Printf("failed to read plugin folder %q: %s\n", pluginFolder, err)
		return 1
	}

	var (
		context   Context
		unmatched = make(map[string][]string)
	)

	for _, file := range files {
		if !strings.HasSuffix(file.Name(), ".json") {
			continue
		}

		filepath := fmt.Sprintf("%s/%s", pluginFolder, file.Name())

		data, err := ioutil.ReadFile(filepath)
		if err != nil {
			fmt.Printf("failed to read plugin file %q: %s\n", filepath, err)
			return 1
		}

		var languageMapping map[string]string

		err = json.Unmarshal(data, &languageMapping)
		if err != nil {
			fmt.Printf("failed to unmarshal data from plugin file %q: %s\n", filepath, err)
			return 1
		}

		plugin := strings.Split(file.Name(), ".")[0]

		// validate languages
		for _, language := range languageMapping {
			if _, ok := heartbeat.ParseLanguage(language); !ok {
				unmatched[plugin] = append(unmatched[plugin], language)
			}
		}

		if plugin == "default" {
			context.Default = languageMapping
			continue
		}

		context.Plugins = append(context.Plugins, Plugin{
			Name:    plugin,
			Title:   strings.Title(plugin),
			Mapping: languageMapping,
		})
	}

	if len(unmatched) > 0 {
		for plugin, languages := range unmatched {
			sort.Strings(languages)

			fmt.Printf(
				"failed to detect the following language(s) for plugin %s: '%s'\n",
				plugin,
				strings.Join(languages, "', '"),
			)
		}

		return 1
	}

	if context.Default == nil {
		fmt.Printf("Could not find default mapping. File 'default.json' not found in %q\n", pluginFolder)
		return 1
	}

	f, err := os.OpenFile(outputFile, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0600)
	if err != nil {
		fmt.Printf("opening output file %s failed: %s\n", outputFile, err)
		return 1
	}
	defer f.Close()

	err = tpl.Execute(f, context)
	if err != nil {
		fmt.Printf("executing text template failed: %s\n", err)
		return 1
	}

	return 0
}

// Context represents the data for rendering a template.
type Context struct {
	Plugins []Plugin
	Default PluginMapping
}

// Plugin represents plugin specific data.
type Plugin struct {
	Name    string
	Title   string
	Mapping PluginMapping
}

// PluginMapping contains plugin specific language spellings.
type PluginMapping map[string]string

// nolint: gochecknoglobals
var tpl = template.Must(template.New("").Parse(`// Code generated by ./cmd/generate/main.go; DO NOT EDIT.
package language

import (
	"strings"

	"github.com/wakatime/wakatime-cli/pkg/heartbeat"
)

// Parse parses the language from a plugin specific string.
func Parse(language, plugin string) (heartbeat.Language, bool) {
	switch strings.ToLower(plugin) {
	{{ range .Plugins }}case "{{ .Name }}":
		return parse{{ .Title }}(language)
	{{ end }}default:
		return parseDefault(language)
	}
}

func parseDefault(language string) (heartbeat.Language, bool) {
	switch strings.ToLower(language) {
	{{ range $key, $value := .Default }}case strings.ToLower("{{ $key }}"):
		return heartbeat.ParseLanguage("{{ $value }}")
	{{ end }}default:
		return heartbeat.LanguageUnknown, false
	}
}

{{ range .Plugins }}func parse{{ .Title }}(language string) (heartbeat.Language, bool) {
	switch strings.ToLower(language) {
	{{ range $key, $value := .Mapping }}case strings.ToLower("{{ $key }}"):
		return heartbeat.ParseLanguage("{{ $value }}")
	{{ end }}default:
		return heartbeat.LanguageUnknown, false
	}
}
{{ end }}`))
