package heartbeat_test

import (
	"fmt"
	"testing"

	"github.com/wakatime/wakatime-cli/pkg/heartbeat"

	"github.com/alecthomas/chroma/v2/lexers"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func languageTests() map[string]heartbeat.Language {
	return map[string]heartbeat.Language{
		"1C Enterprise":                    heartbeat.Language1CEnterprise,
		"4D":                               heartbeat.Language4D,
		"ABAP":                             heartbeat.LanguageABAP,
		"ABNF":                             heartbeat.LanguageABNF,
		"ActionScript":                     heartbeat.LanguageActionScript,
		"ActionScript 3":                   heartbeat.LanguageActionScript3,
		"Ada":                              heartbeat.LanguageAda,
		"ADL":                              heartbeat.LanguageADL,
		"Adobe Font Metrics":               heartbeat.LanguageAdobeFontMetrics,
		"AdvPL":                            heartbeat.LanguageAdvPL,
		"Agda":                             heartbeat.LanguageAgda,
		"AGS Script":                       heartbeat.LanguageAGSScript,
		"Aheui":                            heartbeat.LanguageAheui,
		"AL":                               heartbeat.LanguageAL,
		"Alloy":                            heartbeat.LanguageAlloy,
		"Alpine Abuild":                    heartbeat.LanguageAlpineAbuild,
		"Altium Designer":                  heartbeat.LanguageAltiumDesigner,
		"AmbientTalk":                      heartbeat.LanguageAmbientTalk,
		"AMPL":                             heartbeat.LanguageAMPL,
		"AngelScript":                      heartbeat.LanguageAngelScript,
		"Angular2":                         heartbeat.LanguageAngular2,
		"Ansible":                          heartbeat.LanguageAnsible,
		"Ant Build System":                 heartbeat.LanguageAntBuildSystem,
		"ANTLR":                            heartbeat.LanguageANTLR,
		"Apache Config":                    heartbeat.LanguageApacheConfig,
		"Apex":                             heartbeat.LanguageApex,
		"API Blueprint":                    heartbeat.LanguageAPIBlueprint,
		"APL":                              heartbeat.LanguageAPL,
		"Apollo Guidance Computer":         heartbeat.LanguageApolloGuidanceComputer,
		"AppleScript":                      heartbeat.LanguageAppleScript,
		"ArangoDB Query Language":          heartbeat.LanguageArangoDBQueryLanguage,
		"Arc":                              heartbeat.LanguageArc,
		"Arduino":                          heartbeat.LanguageArduino,
		"ArmAsm":                           heartbeat.LanguageArmAsm,
		"Arrow":                            heartbeat.LanguageArrow,
		"AsciiDoc":                         heartbeat.LanguageASCIIDoc,
		"ASL":                              heartbeat.LanguageASL,
		"ASN.1":                            heartbeat.LanguageASN1,
		"ASP.NET":                          heartbeat.LanguageASPDotNet,
		"AspectJ":                          heartbeat.LanguageAspectJ,
		"aspx-cs":                          heartbeat.LanguageAspxCSharp,
		"aspx-vb":                          heartbeat.LanguageAspxVBNet,
		"Assembly":                         heartbeat.LanguageAssembly,
		"Astro":                            heartbeat.LanguageAstro,
		"Asymptote":                        heartbeat.LanguageAsymptote,
		"ATL":                              heartbeat.LanguageATL,
		"ATS":                              heartbeat.LanguageATS,
		"Augeas":                           heartbeat.LanguageAugeas,
		"Autoconf":                         heartbeat.LanguageAutoconf,
		"AutoHotkey":                       heartbeat.LanguageAutoHotkey,
		"AutoIt":                           heartbeat.LanguageAutoIt,
		"Avro IDL":                         heartbeat.LanguageAvroIDL,
		"Awk":                              heartbeat.LanguageAwk,
		"Ballerina":                        heartbeat.LanguageBallerina,
		"BARE":                             heartbeat.LanguageBARE,
		"Bash":                             heartbeat.LanguageBash,
		"Bash Session":                     heartbeat.LanguageBashSession,
		"Basic":                            heartbeat.LanguageBasic,
		"Batchfile":                        heartbeat.LanguageBatchfile,
		"BBC Basic":                        heartbeat.LanguageBBCBasic,
		"BBCode":                           heartbeat.LanguageBBCode,
		"BC":                               heartbeat.LanguageBC,
		"Beef":                             heartbeat.LanguageBeef,
		"Befunge":                          heartbeat.LanguageBefunge,
		"BibTeX":                           heartbeat.LanguageBibTeX,
		"Bicep":                            heartbeat.LanguageBicep,
		"Bison":                            heartbeat.LanguageBison,
		"BitBake":                          heartbeat.LanguageBitBake,
		"Blade":                            heartbeat.LanguageBlade,
		"Blade Template":                   heartbeat.LanguageBladeTemplate,
		"Blazor":                           heartbeat.LanguageBlazor,
		"BlitzBasic":                       heartbeat.LanguageBlitzBasic,
		"BlitzMax":                         heartbeat.LanguageBlitzMax,
		"Bluespec":                         heartbeat.LanguageBluespec,
		"BNF":                              heartbeat.LanguageBNF,
		"Boa":                              heartbeat.LanguageBoa,
		"Boo":                              heartbeat.LanguageBoo,
		"Boogie":                           heartbeat.LanguageBoogie,
		"BQN":                              heartbeat.LanguageBQN,
		"Brainfuck":                        heartbeat.LanguageBrainfuck,
		"BrightScript":                     heartbeat.LanguageBrightScript,
		"Bro":                              heartbeat.LanguageBro,
		"Browserslist":                     heartbeat.LanguageBrowserslist,
		"BST":                              heartbeat.LanguageBST,
		"BUGS":                             heartbeat.LanguageBUGS,
		"C":                                heartbeat.LanguageC,
		"C#":                               heartbeat.LanguageCSharp,
		"C++":                              heartbeat.LanguageCPP,
		"C-ObjDump":                        heartbeat.LanguageCObjdump,
		"C2hs Haskell":                     heartbeat.LanguageC2hsHaskell,
		"C3":                               heartbeat.LanguageC3,
		"ca65 assembler":                   heartbeat.LanguageCa65Assembler,
		"Cabal Config":                     heartbeat.LanguageCabalConfig,
		"Caddyfile":                        heartbeat.LanguageCaddyfile,
		"Caddyfile Directives":             heartbeat.LanguageCaddyfileDirectives,
		"cADL":                             heartbeat.LanguageCADL,
		"CAmkES":                           heartbeat.LanguageCAmkES,
		"Cap'n Proto":                      heartbeat.LanguageCapNProto,
		"CapDL":                            heartbeat.LanguageCapDL,
		"CartoCSS":                         heartbeat.LanguageCartoCSS,
		"Cassandra CQL":                    heartbeat.LanguageCassandraCQL,
		"CBM BASIC V2":                     heartbeat.LanguageCBMBasicV2,
		"Ceylon":                           heartbeat.LanguageCeylon,
		"CFEngine3":                        heartbeat.LanguageCFEngine3,
		"cfstatement":                      heartbeat.LanguageCfstatement,
		"ChaiScript":                       heartbeat.LanguageChaiScript,
		"Chapel":                           heartbeat.LanguageChapel,
		"Charity":                          heartbeat.LanguageCharity,
		"Charmci":                          heartbeat.LanguageCharmci,
		"Cheetah":                          heartbeat.LanguageCheetah,
		"ChucK":                            heartbeat.LanguageChucK,
		"Cirru":                            heartbeat.LanguageCirru,
		"Clarion":                          heartbeat.LanguageClarion,
		"Classic ASP":                      heartbeat.LanguageClassicASP,
		"Clay":                             heartbeat.LanguageClay,
		"Clean":                            heartbeat.LanguageClean,
		"Click":                            heartbeat.LanguageClick,
		"CLIPS":                            heartbeat.LanguageCLIPS,
		"Clojure":                          heartbeat.LanguageClojure,
		"ClojureScript":                    heartbeat.LanguageClojureScript,
		"Closure Templates":                heartbeat.LanguageClosureTemplates,
		"Cloud Firestore Security Rules":   heartbeat.LanguageCloudFirestoreSecurityRules,
		"CMake":                            heartbeat.LanguageCMake,
		"COBOL":                            heartbeat.LanguageCOBOL,
		"COBOLFree":                        heartbeat.LanguageCOBOLFree,
		"Cocoa":                            heartbeat.LanguageCocoa,
		"CodeQL":                           heartbeat.LanguageCodeQL,
		"CoffeeScript":                     heartbeat.LanguageCoffeeScript,
		"ColdFusion":                       heartbeat.LanguageColdfusionHTML,
		"ColdFusion CFC":                   heartbeat.LanguageColdfusionCFC,
		"COLLADA":                          heartbeat.LanguageCOLLADA,
		"Common Lisp":                      heartbeat.LanguageCommonLisp,
		"Common Workflow Language":         heartbeat.LanguageCommonWorkflowLanguage,
		"Component Pascal":                 heartbeat.LanguageComponentPascal,
		"Config":                           heartbeat.LanguageConfig,
		"CoNLL-U":                          heartbeat.LanguageCoNLLU,
		"Cool":                             heartbeat.LanguageCool,
		"Coq":                              heartbeat.LanguageCoq,
		"Core":                             heartbeat.LanguageCore,
		"cperl":                            heartbeat.LanguageCPerl,
		"Cpp-ObjDump":                      heartbeat.LanguageCppObjdump,
		"CPSA":                             heartbeat.LanguageCPSA,
		"Creole":                           heartbeat.LanguageCreole,
		"Crmsh":                            heartbeat.LanguageCrmsh,
		"Croc":                             heartbeat.LanguageCroc,
		"Crontab":                          heartbeat.LanguageCrontab,
		"Cryptol":                          heartbeat.LanguageCryptol,
		"Crystal":                          heartbeat.LanguageCrystal,
		"CSHTML":                           heartbeat.LanguageCSHTML,
		"CSON":                             heartbeat.LanguageCSON,
		"Csound":                           heartbeat.LanguageCsound,
		"Csound Document":                  heartbeat.LanguageCsoundDocument,
		"Csound Orchestra":                 heartbeat.LanguageCsoundOrchestra,
		"Csound Score":                     heartbeat.LanguageCsoundScore,
		"CSS":                              heartbeat.LanguageCSS,
		"CSV":                              heartbeat.LanguageCSV,
		"Cuda":                             heartbeat.LanguageCUDA,
		"CUE":                              heartbeat.LanguageCUE,
		"cURL Config":                      heartbeat.LanguagecURLConfig,
		"CVS":                              heartbeat.LanguageCVS,
		"CWeb":                             heartbeat.LanguageCWeb,
		"Cycript":                          heartbeat.LanguageCycript,
		"Cypher":                           heartbeat.LanguageCypher,
		"Cython":                           heartbeat.LanguageCython,
		"D":                                heartbeat.LanguageD,
		"d-objdump":                        heartbeat.LanguageDObjdump,
		"Dafny":                            heartbeat.LanguageDafny,
		"Darcs Patch":                      heartbeat.LanguageDarcsPatch,
		"Dart":                             heartbeat.LanguageDart,
		"DASM16":                           heartbeat.LanguageDASM16,
		"DataWeave":                        heartbeat.LanguageDataWeave,
		"Dax":                              heartbeat.LanguageDax,
		"DCL":                              heartbeat.LanguageDCL,
		"DCPU-16 ASM":                      heartbeat.LanguageDCPU16Asm,
		"Debian Control file":              heartbeat.LanguageDebianControlFile,
		"Debian Sourcelist":                heartbeat.LanguageSourcesList,
		"Delphi":                           heartbeat.LanguageDelphi,
		"Desktop file":                     heartbeat.LanguageDesktopFile,
		"Devicetree":                       heartbeat.LanguageDevicetree,
		"dg":                               heartbeat.LanguageDG,
		"Dhall":                            heartbeat.LanguageDhall,
		"Diff":                             heartbeat.LanguageDiff,
		"DIGITAL Command Language":         heartbeat.LanguageDigitalCommand,
		"dircolors":                        heartbeat.LanguageDircolors,
		"DirectX 3D File":                  heartbeat.LanguageDirectX3DFile,
		"Django/Jinja":                     heartbeat.LanguageDjangoJinja,
		"DM":                               heartbeat.LanguageDM,
		"DNS Zone":                         heartbeat.LanguageDNSZone,
		"Docker":                           heartbeat.LanguageDocker,
		"Dockerfile":                       heartbeat.LanguageDockerfile,
		"DocTeX":                           heartbeat.LanguageDocTeX,
		"Documentation":                    heartbeat.LanguageDocumentation,
		"Dogescript":                       heartbeat.LanguageDogescript,
		"DTD":                              heartbeat.LanguageDTD,
		"DTrace":                           heartbeat.LanguageDTrace,
		"Duel":                             heartbeat.LanguageDuel,
		"Dylan":                            heartbeat.LanguageDylan,
		"Dylan session":                    heartbeat.LanguageDylanSession,
		"DylanLID":                         heartbeat.LanguageDylanLID,
		"DynASM":                           heartbeat.LanguageDynASM,
		"E":                                heartbeat.LanguageE,
		"E-mail":                           heartbeat.LanguageEMail,
		"Eagle":                            heartbeat.LanguageEagle,
		"Earl Grey":                        heartbeat.LanguageEarlGrey,
		"Easybuild":                        heartbeat.LanguageEasybuild,
		"Easytrieve":                       heartbeat.LanguageEasytrieve,
		"EBNF":                             heartbeat.LanguageEBNF,
		"eC":                               heartbeat.LanguageEC,
		"Ecere Projects":                   heartbeat.LanguageEcereProjects,
		"ECL":                              heartbeat.LanguageECL,
		"ECLiPSe":                          heartbeat.LanguageEclipse,
		"EditorConfig":                     heartbeat.LanguageEditorConfig,
		"Edje Data Collection":             heartbeat.LanguageEdjeDataCollection,
		"edn":                              heartbeat.LanguageEdn,
		"Eiffel":                           heartbeat.LanguageEiffel,
		"EJS":                              heartbeat.LanguageEJS,
		"Elixir":                           heartbeat.LanguageElixir,
		"Elixir iex session":               heartbeat.LanguageElixirIexSession,
		"Elm":                              heartbeat.LanguageElm,
		"Emacs Lisp":                       heartbeat.LanguageEmacsLisp,
		"Embedded Ragel":                   heartbeat.LanguageRagelEmbedded,
		"EmberScript":                      heartbeat.LanguageEmberScript,
		"EML":                              heartbeat.LanguageEML,
		"EQ":                               heartbeat.LanguageEQ,
		"ERB":                              heartbeat.LanguageERB,
		"Erlang":                           heartbeat.LanguageErlang,
		"Erlang erl session":               heartbeat.LanguageErlangErlSession,
		"Eshell":                           heartbeat.LanguageEshell,
		"Evoque":                           heartbeat.LanguageEvoque,
		"execline":                         heartbeat.LanguageExecline,
		"Ezhil":                            heartbeat.LanguageEzhil,
		"F#":                               heartbeat.LanguageFSharp,
		"F*":                               heartbeat.LanguageFStar,
		"Factor":                           heartbeat.LanguageFactor,
		"Fancy":                            heartbeat.LanguageFancy,
		"Fantom":                           heartbeat.LanguageFantom,
		"Faust":                            heartbeat.LanguageFaust,
		"Felix":                            heartbeat.LanguageFelix,
		"Fennel":                           heartbeat.LanguageFennel,
		"FIGlet Font":                      heartbeat.LanguageFIGletFont,
		"Filebench WML":                    heartbeat.LanguageFilebenchWML,
		"Filterscript":                     heartbeat.LanguageFilterscript,
		"Fish":                             heartbeat.LanguageFish,
		"Flatline":                         heartbeat.LanguageFlatline,
		"FloScript":                        heartbeat.LanguageFloScript,
		"FLUX":                             heartbeat.LanguageFLUX,
		"Font":                             heartbeat.LanguageFont,
		"Formatted":                        heartbeat.LanguageFormatted,
		"Forth":                            heartbeat.LanguageForth,
		"Fortran":                          heartbeat.LanguageFortran,
		"Fortran Free Form":                heartbeat.LanguageFortranFreeForm,
		"FortranFixed":                     heartbeat.LanguageFortranFixed,
		"FoxPro":                           heartbeat.LanguageFoxPro,
		"Freefem":                          heartbeat.LanguageFreefem,
		"FreeMarker":                       heartbeat.LanguageFreeMarker,
		"Frege":                            heartbeat.LanguageFrege,
		"Futhark":                          heartbeat.LanguageFuthark,
		"G-code":                           heartbeat.LanguageGCode,
		"Game Maker Language":              heartbeat.LanguageGameMakerLanguage,
		"GAML":                             heartbeat.LanguageGAML,
		"GAMS":                             heartbeat.LanguageGAMS,
		"GAP":                              heartbeat.LanguageGap,
		"GAS":                              heartbeat.LanguageGas,
		"GCC Machine Description":          heartbeat.LanguageGCCMachineDescription,
		"GDB":                              heartbeat.LanguageGDB,
		"GDNative":                         heartbeat.LanguageGDNative,
		"GDScript":                         heartbeat.LanguageGDScript,
		"GDScript3":                        heartbeat.LanguageGDScript3,
		"GEDCOM":                           heartbeat.LanguageGEDCOM,
		"Gemtext":                          heartbeat.LanguageGemtext,
		"Genie":                            heartbeat.LanguageGenie,
		"Genshi":                           heartbeat.LanguageGenshi,
		"Genshi HTML":                      heartbeat.LanguageGenshiHTML,
		"Genshi Text":                      heartbeat.LanguageGenshiText,
		"Gentoo Ebuild":                    heartbeat.LanguageGentooEbuild,
		"Gentoo Eclass":                    heartbeat.LanguageGentooEclass,
		"Gerber Image":                     heartbeat.LanguageGerberImage,
		"Gettext Catalog":                  heartbeat.LanguageGettextCatalog,
		"Gherkin":                          heartbeat.LanguageGherkin,
		"Git":                              heartbeat.LanguageGit,
		"Git Attributes":                   heartbeat.LanguageGitAttributes,
		"Git Config":                       heartbeat.LanguageGitConfig,
		"Gleam":                            heartbeat.LanguageGleam,
		"GLSL":                             heartbeat.LanguageGLSL,
		"Glyph":                            heartbeat.LanguageGlyph,
		"Glyph Bitmap Distribution Format": heartbeat.LanguageGlyphBitmap,
		"GN":                               heartbeat.LanguageGN,
		"Gnuplot":                          heartbeat.LanguageGnuplot,
		"Go":                               heartbeat.LanguageGo,
		"Go HTML Template":                 heartbeat.LanguageGoHTMLTemplate,
		"Go Template":                      heartbeat.LanguageGoTemplate,
		"Go Text Template":                 heartbeat.LanguageGoTextTemplate,
		"Golo":                             heartbeat.LanguageGolo,
		"GoodData-CL":                      heartbeat.LanguageGoodDataCL,
		"Gosu":                             heartbeat.LanguageGosu,
		"Gosu Template":                    heartbeat.LanguageGosuTemplate,
		"Grace":                            heartbeat.LanguageGrace,
		"Gradle":                           heartbeat.LanguageGradle,
		"Gradle Config":                    heartbeat.LanguageGradleConfig,
		"Grammatical Framework":            heartbeat.LanguageGrammaticalFramework,
		"Graph Modeling Language":          heartbeat.LanguageGraphModelingLanguage,
		"GraphQL":                          heartbeat.LanguageGraphQL,
		"Graphviz (DOT)":                   heartbeat.LanguageGraphvizDOT,
		"Groff":                            heartbeat.LanguageGroff,
		"Groovy":                           heartbeat.LanguageGroovy,
		"Groovy Server Pages":              heartbeat.LanguageGroovyServerPages,
		"Hack":                             heartbeat.LanguageHack,
		"Haml":                             heartbeat.LanguageHaml,
		"Handlebars":                       heartbeat.LanguageHandlebars,
		"HAProxy":                          heartbeat.LanguageHAProxy,
		"Harbour":                          heartbeat.LanguageHarbour,
		"Hare":                             heartbeat.LanguageHare,
		"Haskell":                          heartbeat.LanguageHaskell,
		"Haxe":                             heartbeat.LanguageHaxe,
		"HCL":                              heartbeat.LanguageHCL,
		"Hexdump":                          heartbeat.LanguageHexdump,
		"HiveQL":                           heartbeat.LanguageHiveQL,
		"HLB":                              heartbeat.LanguageHLB,
		"HLSL":                             heartbeat.LanguageHLSL,
		"HolyC":                            heartbeat.LanguageHolyC,
		"HSAIL":                            heartbeat.LanguageHSAIL,
		"Hspec":                            heartbeat.LanguageHspec,
		"HTML":                             heartbeat.LanguageHTML,
		"HTML+Django":                      heartbeat.LanguageHTMLDjango,
		"HTML+ECR":                         heartbeat.LanguageHTMLECR,
		"HTML+EEX":                         heartbeat.LanguageHTMLEEX,
		"HTML+ERB":                         heartbeat.LanguageHTMLERB,
		"HTML+PHP":                         heartbeat.LanguageHTMLPHP,
		"HTML+Razor":                       heartbeat.LanguageHTMLRazor,
		"HTTP":                             heartbeat.LanguageHTTP,
		"HXML":                             heartbeat.LanguageHxml,
		"Hy":                               heartbeat.LanguageHy,
		"Hybris":                           heartbeat.LanguageHybris,
		"HyPhy":                            heartbeat.LanguageHyPhy,
		"Icon":                             heartbeat.LanguageIcon,
		"IDA":                              heartbeat.LanguageIDA,
		"IDL":                              heartbeat.LanguageIDL,
		"Idris":                            heartbeat.LanguageIdris,
		"Ignore List":                      heartbeat.LanguageIgnoreList,
		"Igor":                             heartbeat.LanguageIgor,
		"IGOR Pro":                         heartbeat.LanguageIGORPro,
		"Image (jpeg)":                     heartbeat.LanguageImageJPEG,
		"Image (png)":                      heartbeat.LanguageImagePNG,
		"ImageJ Macro":                     heartbeat.LanguageImageJMacro,
		"Inform 6":                         heartbeat.LanguageInform6,
		"Inform 6 template":                heartbeat.LanguageInform6Template,
		"Inform 7":                         heartbeat.LanguageInform7,
		"INI":                              heartbeat.LanguageINI,
		"Inno Setup":                       heartbeat.LanguageInnoSetup,
		"Io":                               heartbeat.LanguageIo,
		"Ioke":                             heartbeat.LanguageIoke,
		"IRC Logs":                         heartbeat.LanguageIRCLogs,
		"Isabelle":                         heartbeat.LanguageIsabelle,
		"Isabelle ROOT":                    heartbeat.LanguageIsabelleRoot,
		"ISC dhcpd":                        heartbeat.LanguageISCdhcpd,
		"J":                                heartbeat.LanguageJ,
		"Jade":                             heartbeat.LanguageJade,
		"JAGS":                             heartbeat.LanguageJAGS,
		"Janet":                            heartbeat.LanguageJanet,
		"Jasmin":                           heartbeat.LanguageJasmin,
		"Java":                             heartbeat.LanguageJava,
		"Java Properties":                  heartbeat.LanguageJavaProperties,
		"Java Server Page":                 heartbeat.LanguageJSP,
		"JavaScript":                       heartbeat.LanguageJavaScript,
		"JavaScript+ERB":                   heartbeat.LanguageJavaScriptERB,
		"JCL":                              heartbeat.LanguageJCL,
		"JFlex":                            heartbeat.LanguageJFlex,
		"Jison":                            heartbeat.LanguageJison,
		"Jison Lex":                        heartbeat.LanguageJisonLex,
		"Jolie":                            heartbeat.LanguageJolie,
		"JSGF":                             heartbeat.LanguageJSGF,
		"JSON":                             heartbeat.LanguageJSON,
		"JSON with Comments":               heartbeat.LanguageJSONWithComments,
		"JSON5":                            heartbeat.LanguageJSON5,
		"JSONata":                          heartbeat.LanguageJSONata,
		"JSONiq":                           heartbeat.LanguageJSONiq,
		"JSONLD":                           heartbeat.LanguageJSONLD,
		"Jsonnet":                          heartbeat.LanguageJsonnet,
		"JSX":                              heartbeat.LanguageJSX,
		"Julia":                            heartbeat.LanguageJulia,
		"Julia console":                    heartbeat.LanguageJuliaConsole,
		"Jungle":                           heartbeat.LanguageJungle,
		"Jupyter Notebook":                 heartbeat.LanguageJupyterNotebook,
		"Juttle":                           heartbeat.LanguageJuttle,
		"Kaitai Struct":                    heartbeat.LanguageKaitai,
		"Kakoune":                          heartbeat.LanguageKakoune,
		"Kal":                              heartbeat.LanguageKal,
		"Kconfig":                          heartbeat.LanguageKconfig,
		"Kernel log":                       heartbeat.LanguageKernelLog,
		"KiCad Layout":                     heartbeat.LanguageKiCadLayout,
		"KiCad Legacy Layout":              heartbeat.LanguageKiCadLegacyLayout,
		"KiCad Schematic":                  heartbeat.LanguageKiCadSchematic,
		"Kit":                              heartbeat.LanguageKit,
		"Koka":                             heartbeat.LanguageKoka,
		"Kotlin":                           heartbeat.LanguageKotlin,
		"KRL":                              heartbeat.LanguageKRL,
		"LabVIEW":                          heartbeat.LanguageLabVIEW,
		"Laravel Template":                 heartbeat.LanguageLaravelTemplate,
		"Lark":                             heartbeat.LanguageLark,
		"Lasso":                            heartbeat.LanguageLasso,
		"LaTeX":                            heartbeat.LanguageLaTeX,
		"Latte":                            heartbeat.LanguageLatte,
		"Lean":                             heartbeat.LanguageLean,
		"Lean4":                            heartbeat.LanguageLean4,
		"LESS":                             heartbeat.LanguageLess,
		"Lex":                              heartbeat.LanguageLex,
		"LFE":                              heartbeat.LanguageLFE,
		"Lighttpd configuration file":      heartbeat.LanguageLighttpd,
		"LilyPond":                         heartbeat.LanguageLilyPond,
		"Limbo":                            heartbeat.LanguageLimbo,
		"Linker Script":                    heartbeat.LanguageLinkerScript,
		"Linux Kernel Module":              heartbeat.LanguageLinuxKernelModule,
		"Liquid":                           heartbeat.LanguageLiquid,
		"Literate Agda":                    heartbeat.LanguageLiterateAgda,
		"Literate CoffeeScript":            heartbeat.LanguageLiterateCoffeeScript,
		"Literate Cryptol":                 heartbeat.LanguageLiterateCryptol,
		"Literate Haskell":                 heartbeat.LanguageLiterateHaskell,
		"Literate Idris":                   heartbeat.LanguageLiterateIdris,
		"LiveScript":                       heartbeat.LanguageLiveScript,
		"LLVM":                             heartbeat.LanguageLLVM,
		"LLVM-MIR":                         heartbeat.LanguageLLVMMIR,
		"LLVM-MIR Body":                    heartbeat.LanguageLLVMMIRBody,
		"Log File":                         heartbeat.LanguageLogFile,
		"Logos":                            heartbeat.LanguageLogos,
		"Logtalk":                          heartbeat.LanguageLogtalk,
		"LOLCODE":                          heartbeat.LanguageLOLCODE,
		"LookML":                           heartbeat.LanguageLookML,
		"LoomScript":                       heartbeat.LanguageLoomScript,
		"lox":                              heartbeat.LanguageLox,
		"LSL":                              heartbeat.LanguageLSL,
		"LTspice Symbol":                   heartbeat.LanguageLTspiceSymbol,
		"Lua":                              heartbeat.LanguageLua,
		"Makefile":                         heartbeat.LanguageMakefile,
		"Mako":                             heartbeat.LanguageMako,
		"Man":                              heartbeat.LanguageMan,
		"MAQL":                             heartbeat.LanguageMAQL,
		"Markdown":                         heartbeat.LanguageMarkdown,
		"Marko":                            heartbeat.LanguageMarko,
		"Mask":                             heartbeat.LanguageMask,
		"Mason":                            heartbeat.LanguageMason,
		"Materialize SQL dialect":          heartbeat.LanguageMaterializeSQLDialect,
		"Mathematica":                      heartbeat.LanguageMathematica,
		"Matlab":                           heartbeat.LanguageMatlab,
		"Matlab session":                   heartbeat.LanguageMatlabSession,
		"Max":                              heartbeat.LanguageMax,
		"Max/MSP":                          heartbeat.LanguageMaxMSP,
		"MCFunction":                       heartbeat.LanguageMCFunction,
		"Meson":                            heartbeat.LanguageMeson,
		"Metafont":                         heartbeat.LanguageMetafont,
		"Metal":                            heartbeat.LanguageMetal,
		"Metapost":                         heartbeat.LanguageMetapost,
		"MIME":                             heartbeat.LanguageMIME,
		"MiniD":                            heartbeat.LanguageMiniD,
		"MiniScript":                       heartbeat.LanguageMiniScript,
		"MiniZinc":                         heartbeat.LanguageMiniZinc,
		"Mirah":                            heartbeat.LanguageMirah,
		"MLIR":                             heartbeat.LanguageMLIR,
		"Modelica":                         heartbeat.LanguageModelica,
		"Modula-2":                         heartbeat.LanguageModula2,
		"MoinMoin/Trac Wiki markup":        heartbeat.LanguageMoinWiki,
		"Mojo":                             heartbeat.LanguageMojo,
		"Monkey":                           heartbeat.LanguageMonkey,
		"MonkeyC":                          heartbeat.LanguageMonkeyC,
		"Monte":                            heartbeat.LanguageMonte,
		"MOOCode":                          heartbeat.LanguageMOOCode,
		"MoonScript":                       heartbeat.LanguageMoonScript,
		"MorrowindScript":                  heartbeat.LanguageMorrowindScript,
		"Mosel":                            heartbeat.LanguageMosel,
		"mozhashpreproc":                   heartbeat.LanguageMozPreprocHash,
		"mozpercentpreproc":                heartbeat.LanguageMozPreprocPercent,
		"MQL":                              heartbeat.LanguageMQL,
		"Mscgen":                           heartbeat.LanguageMscgen,
		"MSDOS Session":                    heartbeat.LanguageMSDOSSession,
		"MuPAD":                            heartbeat.LanguageMuPAD,
		"Mustache":                         heartbeat.LanguageMustache,
		"MXML":                             heartbeat.LanguageMXML,
		"Myghty":                           heartbeat.LanguageMyghty,
		"MySQL":                            heartbeat.LanguageMySQL,
		"NASM":                             heartbeat.LanguageNASM,
		"Natural":                          heartbeat.LanguageNatural,
		"NCL":                              heartbeat.LanguageNCL,
		"NDISASM":                          heartbeat.LanguageNDISASM,
		"Nemerle":                          heartbeat.LanguageNemerle,
		"Neon":                             heartbeat.LanguageNeon,
		"nesC":                             heartbeat.LanguageNesC,
		"newLisp":                          heartbeat.LanguageNewLisp,
		"Newspeak":                         heartbeat.LanguageNewspeak,
		"Nginx":                            heartbeat.LanguageNginx,
		"Nginx configuration file":         heartbeat.LanguageNginxConfig,
		"Nimrod":                           heartbeat.LanguageNimrod,
		"Nit":                              heartbeat.LanguageNit,
		"Nix":                              heartbeat.LanguageNix,
		"Notmuch":                          heartbeat.LanguageNotmuch,
		"NSIS":                             heartbeat.LanguageNSIS,
		"Nu":                               heartbeat.LanguageNu,
		"NumPy":                            heartbeat.LanguageNumPy,
		"Nushell":                          heartbeat.LanguageNushell,
		"NuSMV":                            heartbeat.LanguageNuSMV,
		"objdump":                          heartbeat.LanguageObjdump,
		"objdump-nasm":                     heartbeat.LanguageNASMObjdump,
		"Objective-C":                      heartbeat.LanguageObjectiveC,
		"Objective-C++":                    heartbeat.LanguageObjectiveCPP,
		"Objective-J":                      heartbeat.LanguageObjectiveJ,
		"ObjectPascal":                     heartbeat.LanguageObjectPascal,
		"OCaml":                            heartbeat.LanguageOCaml,
		"Octave":                           heartbeat.LanguageOctave,
		"Odin":                             heartbeat.LanguageODIN,
		"OnesEnterprise":                   heartbeat.LanguageOnesEnterprise,
		"ooc":                              heartbeat.LanguageOoc,
		"Opa":                              heartbeat.LanguageOpa,
		"OpenEdge ABL":                     heartbeat.LanguageOpenEdgeABL,
		"OpenSCAD":                         heartbeat.LanguageOpenSCAD,
		"Org":                              heartbeat.LanguageOrg,
		"PacmanConf":                       heartbeat.LanguagePacmanConf,
		"Pan":                              heartbeat.LanguagePan,
		"ParaSail":                         heartbeat.LanguageParaSail,
		"Parrot":                           heartbeat.LanguageParrot,
		"Pascal":                           heartbeat.LanguagePascal,
		"Pawn":                             heartbeat.LanguagePawn,
		"PEG":                              heartbeat.LanguagePEG,
		"Perl":                             heartbeat.LanguagePerl,
		"Perl6":                            heartbeat.LanguagePerl6,
		"PHP":                              heartbeat.LanguagePHP,
		"PHTML":                            heartbeat.LanguagePHTML,
		"Pig":                              heartbeat.LanguagePig,
		"Pike":                             heartbeat.LanguagePike,
		"PkgConfig":                        heartbeat.LanguagePkgConfig,
		"PL/pgSQL":                         heartbeat.LanguagePLpgSQL,
		"Plutus Core":                      heartbeat.LanguagePlutusCore,
		"Pointless":                        heartbeat.LanguagePointless,
		"Pony":                             heartbeat.LanguagePony,
		"PostgreSQL console (psql)":        heartbeat.LanguagePostgresConsole,
		"PostgreSQL SQL dialect":           heartbeat.LanguagePostgres,
		"PostScript":                       heartbeat.LanguagePostScript,
		"POVRay":                           heartbeat.LanguagePOVRay,
		"PowerQuery":                       heartbeat.LanguagePowerQuery,
		"PowerShell":                       heartbeat.LanguagePowerShell,
		"PowerShell Session":               heartbeat.LanguagePowerShellSession,
		"Praat":                            heartbeat.LanguagePraat,
		"Processing":                       heartbeat.LanguageProcessing,
		"Prolog":                           heartbeat.LanguageProlog,
		"Promela":                          heartbeat.LanguagePromela,
		"PromQL":                           heartbeat.LanguagePromQL,
		"Property Specification Language":  heartbeat.LanguagePSL,
		"Protocol Buffer":                  heartbeat.LanguageProtocolBuffer,
		"PRQL":                             heartbeat.LanguagePRQL,
		"PsySH console session for PHP":    heartbeat.LanguagePsyShPHP,
		"Pug":                              heartbeat.LanguagePug,
		"Puppet":                           heartbeat.LanguagePuppet,
		"Pure Data":                        heartbeat.LanguagePureData,
		"PureScript":                       heartbeat.LanguagePureScript,
		"PyPy Log":                         heartbeat.LanguagePyPyLog,
		"Python":                           heartbeat.LanguagePython,
		"Python 2":                         heartbeat.LanguagePython2,
		"Python 2.x Traceback":             heartbeat.LanguagePython2Traceback,
		"Python console session":           heartbeat.LanguagePythonConsole,
		"Python Traceback":                 heartbeat.LanguagePythonTraceback,
		"QBasic":                           heartbeat.LanguageQBasic,
		"QML":                              heartbeat.LanguageQML,
		"QVTO":                             heartbeat.LanguageQVTO,
		"R":                                heartbeat.LanguageR,
		"Racket":                           heartbeat.LanguageRacket,
		"Ragel":                            heartbeat.LanguageRagel,
		"Raku":                             heartbeat.LanguageRaku,
		"RAML":                             heartbeat.LanguageRAML,
		"Rascal":                           heartbeat.LanguageRascal,
		"Raw token data":                   heartbeat.LanguageRawToken,
		"Razor":                            heartbeat.LanguageRazor,
		"RConsole":                         heartbeat.LanguageRConsole,
		"Rd":                               heartbeat.LanguageRd,
		"RDoc":                             heartbeat.LanguageRDoc,
		"Readline Config":                  heartbeat.LanguageReadlineConfig,
		"REALbasic":                        heartbeat.LanguageREALbasic,
		"Reason":                           heartbeat.LanguageReasonML,
		"Rebol":                            heartbeat.LanguageREBOL,
		"Record Jar":                       heartbeat.LanguageRecordJar,
		"Red":                              heartbeat.LanguageRed,
		"Redcode":                          heartbeat.LanguageRedcode,
		"reg":                              heartbeat.LanguageRegistry,
		"Rego":                             heartbeat.LanguageRego,
		"Regular Expression":               heartbeat.LanguageRegularExpression,
		"Relax-NG Compact":                 heartbeat.LanguageRNGCompact,
		"Ren'Py":                           heartbeat.LanguageRenPy,
		"RenderScript":                     heartbeat.LanguageRenderScript,
		"ReScript":                         heartbeat.LanguageReScript,
		"ResourceBundle":                   heartbeat.LanguageResourceBundle,
		"reStructuredText":                 heartbeat.LanguageReStructuredText,
		"REXX":                             heartbeat.LanguageRexx,
		"RGBDS Assembly":                   heartbeat.LanguageRGBDSAssembly,
		"RHTML":                            heartbeat.LanguageRHTML,
		"Rich Text Format":                 heartbeat.LanguageRichTextFormat,
		"Ride":                             heartbeat.LanguageRide,
		"Ring":                             heartbeat.LanguageRing,
		"Riot":                             heartbeat.LanguageRiot,
		"RMarkdown":                        heartbeat.LanguageRMarkdown,
		"Roboconf Graph":                   heartbeat.LanguageRoboconfGraph,
		"Roboconf Instances":               heartbeat.LanguageRoboconfInstances,
		"RobotFramework":                   heartbeat.LanguageRobotFramework,
		"Roff":                             heartbeat.LanguageRoff,
		"Roff Manpage":                     heartbeat.LanguageRoffManpage,
		"Rouge":                            heartbeat.LanguageRouge,
		"RPC":                              heartbeat.LanguageRPC,
		"RPGLE":                            heartbeat.LanguageRPGLE,
		"RPMSpec":                          heartbeat.LanguageRPMSpec,
		"RQL":                              heartbeat.LanguageRQL,
		"RSL":                              heartbeat.LanguageRSL,
		"Ruby":                             heartbeat.LanguageRuby,
		"Ruby irb session":                 heartbeat.LanguageRubyIRBSession,
		"RUNOFF":                           heartbeat.LanguageRUNOFF,
		"Rust":                             heartbeat.LanguageRust,
		"S":                                heartbeat.LanguageS,
		"S/MIME":                           heartbeat.LanguageSMIME,
		"Sage":                             heartbeat.LanguageSage,
		"Salt":                             heartbeat.LanguageSalt,
		"SARL":                             heartbeat.LanguageSARL,
		"SAS":                              heartbeat.LanguageSAS,
		"Sass":                             heartbeat.LanguageSass,
		"Scala":                            heartbeat.LanguageScala,
		"Scalate Server Page":              heartbeat.LanguageSSP,
		"Scaml":                            heartbeat.LanguageScaml,
		"scdoc":                            heartbeat.LanguageScdoc,
		"Scheme":                           heartbeat.LanguageScheme,
		"Scilab":                           heartbeat.LanguageScilab,
		"Scribe":                           heartbeat.LanguageScribe,
		"SCSS":                             heartbeat.LanguageSCSS,
		"sed":                              heartbeat.LanguageSed,
		"Self":                             heartbeat.LanguageSelf,
		"SGML":                             heartbeat.LanguageSGML,
		"ShaderLab":                        heartbeat.LanguageShaderLab,
		"Shell":                            heartbeat.LanguageShell,
		"ShellSession":                     heartbeat.LanguageShellSession,
		"Shen":                             heartbeat.LanguageShen,
		"ShExC":                            heartbeat.LanguageShExC,
		"Sieve":                            heartbeat.LanguageSieve,
		"Silver":                           heartbeat.LanguageSilver,
		"Simula":                           heartbeat.LanguageSimula,
		"Singularity":                      heartbeat.LanguageSingularity,
		"Sketch Drawing":                   heartbeat.LanguageSketchDrawing,
		"SKILL":                            heartbeat.LanguageSKILL,
		"Slash":                            heartbeat.LanguageSlash,
		"Slice":                            heartbeat.LanguageSlice,
		"Slim":                             heartbeat.LanguageSlim,
		"Slint":                            heartbeat.LanguageSlint,
		"Slurm":                            heartbeat.LanguageSlurm,
		"Smali":                            heartbeat.LanguageSmali,
		"Smalltalk":                        heartbeat.LanguageSmalltalk,
		"SmartGameFormat":                  heartbeat.LanguageSmartGameFormat,
		"Smarty":                           heartbeat.LanguageSmarty,
		"SmPL":                             heartbeat.LanguageSmPL,
		"SMT":                              heartbeat.LanguageSMT,
		"SNBT":                             heartbeat.LanguageSNBT,
		"Snobol":                           heartbeat.LanguageSnobol,
		"Snowball":                         heartbeat.LanguageSnowball,
		"Solidity":                         heartbeat.LanguageSolidity,
		"SourcePawn":                       heartbeat.LanguageSourcePawn,
		"SPARQL":                           heartbeat.LanguageSPARQL,
		"Spline Font Database":             heartbeat.LanguageSplineFontDatabase,
		"SQF":                              heartbeat.LanguageSQF,
		"SQL":                              heartbeat.LanguageSQL,
		"sqlite3con":                       heartbeat.LanguageSqlite3con,
		"SQLPL":                            heartbeat.LanguageSQLPL,
		"SquidConf":                        heartbeat.LanguageSquidConf,
		"Squirrel":                         heartbeat.LanguageSquirrel,
		"SRecode Template":                 heartbeat.LanguageSRecodeTemplate,
		"SSH Config":                       heartbeat.LanguageSSHConfig,
		"st(ack) as(sembler)":              heartbeat.LanguageStas,
		"Stan":                             heartbeat.LanguageStan,
		"Standard ML":                      heartbeat.LanguageSML,
		"Starlark":                         heartbeat.LanguageStarlark,
		"Stata":                            heartbeat.LanguageStata,
		"STON":                             heartbeat.LanguageSTON,
		"Stylus":                           heartbeat.LanguageStylus,
		"Sublime Text Config":              heartbeat.LanguageSublimeTextConfig,
		"SubRip Text":                      heartbeat.LanguageSubRipText,
		"SugarSS":                          heartbeat.LanguageSugarSS,
		"SuperCollider":                    heartbeat.LanguageSuperCollider,
		"Svelte":                           heartbeat.LanguageSvelte,
		"SVG":                              heartbeat.LanguageSVG,
		"Swift":                            heartbeat.LanguageSwift,
		"SWIG":                             heartbeat.LanguageSWIG,
		"systemd":                          heartbeat.LanguageSYSTEMD,
		"SystemVerilog":                    heartbeat.LanguageSystemVerilog,
		"TableGen":                         heartbeat.LanguageTableGen,
		"TADS 3":                           heartbeat.LanguageTADS3,
		"TAP":                              heartbeat.LanguageTAP,
		"TASM":                             heartbeat.LanguageTASM,
		"Tcl":                              heartbeat.LanguageTcl,
		"Tcsh":                             heartbeat.LanguageTcsh,
		"Tcsh Session":                     heartbeat.LanguageTcshSession,
		"Tea":                              heartbeat.LanguageTea,
		"Tera Term macro":                  heartbeat.LanguageTeraTerm,
		"Termcap":                          heartbeat.LanguageTermcap,
		"Terminfo":                         heartbeat.LanguageTerminfo,
		"Terra":                            heartbeat.LanguageTerra,
		"Terraform":                        heartbeat.LanguageTerraform,
		"TeX":                              heartbeat.LanguageTeX,
		"Texinfo":                          heartbeat.LanguageTexinfo,
		"Text":                             heartbeat.LanguageText,
		"Textile":                          heartbeat.LanguageTextile,
		"Thrift":                           heartbeat.LanguageThrift,
		"TI Program":                       heartbeat.LanguageTIProgram,
		"tiddler":                          heartbeat.LanguageTiddler,
		"TLA":                              heartbeat.LanguageTLA,
		"Todotxt":                          heartbeat.LanguageTodotxt,
		"TOML":                             heartbeat.LanguageTOML,
		"TradingView":                      heartbeat.LanguageTradingView,
		"TrafficScript":                    heartbeat.LanguageTrafficScript,
		"Treetop":                          heartbeat.LanguageTreetop,
		"TSQL":                             heartbeat.LanguageTransactSQL,
		"TSV":                              heartbeat.LanguageTSV,
		"TSX":                              heartbeat.LanguageTSX,
		"Turing":                           heartbeat.LanguageTuring,
		"Turtle":                           heartbeat.LanguageTurtle,
		"Twig":                             heartbeat.LanguageTwig,
		"TXL":                              heartbeat.LanguageTXL,
		"Type Language":                    heartbeat.LanguageTypeLanguage,
		"TypeScript":                       heartbeat.LanguageTypeScript,
		"Typographic Number Theory":        heartbeat.LanguageTNT,
		"TypoScript":                       heartbeat.LanguageTypoScript,
		"Typst":                            heartbeat.LanguageTypst,
		"ucode":                            heartbeat.LanguageUcode,
		"Unicon":                           heartbeat.LanguageUnicon,
		"Unified Parallel C":               heartbeat.LanguageUnifiedParallelC,
		"Unity3D Asset":                    heartbeat.LanguageUnity3DAsset,
		"Unix Assembly":                    heartbeat.LanguageUnixAssembly,
		"Uno":                              heartbeat.LanguageUno,
		"UnrealScript":                     heartbeat.LanguageUnrealScript,
		"UrbiScript":                       heartbeat.LanguageUrbiScript,
		"UrWeb":                            heartbeat.LanguageUrWeb,
		"USD":                              heartbeat.LanguageUSD,
		"Uxntal":                           heartbeat.LanguageUxntal,
		"V":                                heartbeat.LanguageV,
		"V shell":                          heartbeat.LanguageVShell,
		"Vala":                             heartbeat.LanguageVala,
		"VB":                               heartbeat.LanguageVB,
		"VB.NET":                           heartbeat.LanguageVBNet,
		"VBA":                              heartbeat.LanguageVBA,
		"VBScript":                         heartbeat.LanguageVBScript,
		"VCL":                              heartbeat.LanguageVCL,
		"VCLSnippets":                      heartbeat.LanguageVCLSnippets,
		"VCTreeStatus":                     heartbeat.LanguageVCTreeStatus,
		"Velocity":                         heartbeat.LanguageVelocity,
		"Verilog":                          heartbeat.LanguageVerilog,
		"VGL":                              heartbeat.LanguageVGL,
		"VHDL":                             heartbeat.LanguageVHDL,
		"VHS":                              heartbeat.LanguageVHS,
		"Vim Help File":                    heartbeat.LanguageVimHelpFile,
		"Vim Script":                       heartbeat.LanguageVimScript,
		"Vim Snippet":                      heartbeat.LanguageVimSnippet,
		"VimL":                             heartbeat.LanguageVimL,
		"Volt":                             heartbeat.LanguageVolt,
		"Vue.js":                           heartbeat.LanguageVueJS,
		"Wavefront Material":               heartbeat.LanguageWavefrontMaterial,
		"Wavefront Object":                 heartbeat.LanguageWavefrontObject,
		"WDiff":                            heartbeat.LanguageWDiff,
		"wdl":                              heartbeat.LanguageWdl,
		"WDTE":                             heartbeat.LanguageWDTE,
		"Web Ontology Language":            heartbeat.LanguageWebOntologyLanguage,
		"WebAssembly":                      heartbeat.LanguageWebAssembly,
		"WebGPU Shading Language":          heartbeat.LanguageWebGPUShadingLanguage,
		"WebIDL":                           heartbeat.LanguageWebIDL,
		"WebVTT":                           heartbeat.LanguageWebVTT,
		"Wget Config":                      heartbeat.LanguageWgetConfig,
		"Whiley":                           heartbeat.LanguageWhiley,
		"Windows Registry Entries":         heartbeat.LanguageWindowsRegistryEntries,
		"wisp":                             heartbeat.LanguageWisp,
		"Wollok":                           heartbeat.LanguageWollok,
		"World of Warcraft Addon Data":     heartbeat.LanguageWowAddonData,
		"X BitMap":                         heartbeat.LanguageXBitMap,
		"X Font Directory Index":           heartbeat.LanguageXFontDirectoryIndex,
		"X PixMap":                         heartbeat.LanguageXPixMap,
		"X10":                              heartbeat.LanguageX10,
		"XAML":                             heartbeat.LanguageXAML,
		"xBase":                            heartbeat.LanguageXBase,
		"XC":                               heartbeat.LanguageXC,
		"XCompose":                         heartbeat.LanguageXCompose,
		"XML":                              heartbeat.LanguageXML,
		"XML Property List":                heartbeat.LanguageXMLPropertyList,
		"Xojo":                             heartbeat.LanguageXojo,
		"Xorg":                             heartbeat.LanguageXorg,
		"XPages":                           heartbeat.LanguageXPages,
		"XProc":                            heartbeat.LanguageXProc,
		"XQuery":                           heartbeat.LanguageXQuery,
		"XS":                               heartbeat.LanguageXS,
		"XSLT":                             heartbeat.LanguageXSLT,
		"Xtend":                            heartbeat.LanguageXtend,
		"xtlang":                           heartbeat.LanguageXtlang,
		"Yacc":                             heartbeat.LanguageYacc,
		"YAML":                             heartbeat.LanguageYAML,
		"YANG":                             heartbeat.LanguageYANG,
		"YARA":                             heartbeat.LanguageYARA,
		"YASnippet":                        heartbeat.LanguageYASnippet,
		"Z80 Assembly":                     heartbeat.LanguageZ80Assembly,
		"ZAP":                              heartbeat.LanguageZAP,
		"Zed":                              heartbeat.LanguageZed,
		"Zeek":                             heartbeat.LanguageZeek,
		"ZenScript":                        heartbeat.LanguageZenScript,
		"Zephir":                           heartbeat.LanguageZephir,
		"Zig":                              heartbeat.LanguageZig,
		"ZIL":                              heartbeat.LanguageZIL,
		"Zimpl":                            heartbeat.LanguageZimpl,
	}
}

func languageTestsAliases() map[string]heartbeat.Language {
	return map[string]heartbeat.Language{
		"1S":                          heartbeat.LanguageOnesEnterprise,
		"1S:Enterprise":               heartbeat.LanguageOnesEnterprise,
		"abl":                         heartbeat.LanguageOpenEdgeABL,
		"ada2005":                     heartbeat.LanguageAda,
		"ada95":                       heartbeat.LanguageAda,
		"ahk":                         heartbeat.LanguageAutoHotkey,
		"ApacheConf":                  heartbeat.LanguageApacheConfig,
		"apacheconf":                  heartbeat.LanguageApacheConfig,
		"ArangoDB AQL":                heartbeat.LanguageArangoDBQueryLanguage,
		"arexx":                       heartbeat.LanguageRexx,
		"as":                          heartbeat.LanguageActionScript,
		"as3":                         heartbeat.LanguageActionScript3,
		"asm":                         heartbeat.LanguageGas,
		"ASP Classic":                 heartbeat.LanguageClassicASP,
		"b3d":                         heartbeat.LanguageBlitzBasic,
		"bat":                         heartbeat.LanguageBatchfile,
		"batch":                       heartbeat.LanguageBatchfile,
		"Batch Script":                heartbeat.LanguageBatchfile,
		"bf":                          heartbeat.LanguageBrainfuck,
		"bib":                         heartbeat.LanguageBibTeX,
		"bplus":                       heartbeat.LanguageBlitzBasic,
		"bsdmake":                     heartbeat.LanguageMakefile,
		"caddy":                       heartbeat.LanguageCaddyfile,
		"caddy-d":                     heartbeat.LanguageCaddyfileDirectives,
		"caddyfile-d":                 heartbeat.LanguageCaddyfileDirectives,
		"capnp":                       heartbeat.LanguageCapNProto,
		"cassandra":                   heartbeat.LanguageCassandraCQL,
		"cassette":                    heartbeat.LanguageVHS,
		"cf3":                         heartbeat.LanguageCFEngine3,
		"cfg":                         heartbeat.LanguageINI,
		"cfs":                         heartbeat.LanguageCfstatement,
		"chai":                        heartbeat.LanguageChaiScript,
		"chpl":                        heartbeat.LanguageChapel,
		"cl":                          heartbeat.LanguageCommonLisp,
		"clj":                         heartbeat.LanguageClojure,
		"coffee":                      heartbeat.LanguageCoffeeScript,
		"Coldfusion HTML":             heartbeat.LanguageColdfusionHTML,
		"console":                     heartbeat.LanguageBashSession,
		"containerfile":               heartbeat.LanguageDocker,
		"cql":                         heartbeat.LanguageCassandraCQL,
		"cr":                          heartbeat.LanguageCrystal,
		"csh":                         heartbeat.LanguageTcsh,
		"cucumber":                    heartbeat.LanguageGherkin,
		"Cucumber":                    heartbeat.LanguageGherkin,
		"desktop":                     heartbeat.LanguageDesktopFile,
		"desktop_entry":               heartbeat.LanguageDesktopFile,
		"django":                      heartbeat.LanguageDjangoJinja,
		"dns":                         heartbeat.LanguageDNSZone,
		"dosbatch":                    heartbeat.LanguageBatchfile,
		"dosini":                      heartbeat.LanguageINI,
		"dts":                         heartbeat.LanguageDevicetree,
		"duby":                        heartbeat.LanguageRuby,
		"elisp":                       heartbeat.LanguageEmacsLisp,
		"emacs":                       heartbeat.LanguageEmacsLisp,
		"ex":                          heartbeat.LanguageElixir,
		"exs":                         heartbeat.LanguageElixir,
		"f90":                         heartbeat.LanguageFortran,
		"fishshell":                   heartbeat.LanguageFish,
		"fnl":                         heartbeat.LanguageFennel,
		"FStar":                       heartbeat.LanguageFStar,
		"gawk":                        heartbeat.LanguageAwk,
		"gd":                          heartbeat.LanguageGDScript,
		"gd3":                         heartbeat.LanguageGDScript3,
		"gemini":                      heartbeat.LanguageGemtext,
		"gmi":                         heartbeat.LanguageGemtext,
		"gmni":                        heartbeat.LanguageGemtext,
		"golang":                      heartbeat.LanguageGo,
		"gql":                         heartbeat.LanguageGraphQL,
		"graphqls":                    heartbeat.LanguageGraphQL,
		"gsed":                        heartbeat.LanguageSed,
		"hbs":                         heartbeat.LanguageHandlebars,
		"hs":                          heartbeat.LanguageHaskell,
		"html+genshi":                 heartbeat.LanguageGenshiHTML,
		"html+kid":                    heartbeat.LanguageGenshiHTML,
		"hx":                          heartbeat.LanguageHaxe,
		"hxsl":                        heartbeat.LanguageHaxe,
		"hylang":                      heartbeat.LanguageHy,
		"idr":                         heartbeat.LanguageIdris,
		"jinja":                       heartbeat.LanguageDjangoJinja,
		"jl":                          heartbeat.LanguageJulia,
		"js":                          heartbeat.LanguageJavaScript,
		"kak":                         heartbeat.LanguageKakoune,
		"kakrc":                       heartbeat.LanguageKakoune,
		"kakscript":                   heartbeat.LanguageKakoune,
		"kid":                         heartbeat.LanguageGenshi,
		"ksh":                         heartbeat.LanguageBash,
		"LessCss":                     heartbeat.LanguageLess,
		"lighttpd":                    heartbeat.LanguageLighttpd,
		"lighty":                      heartbeat.LanguageLighttpd,
		"lisp":                        heartbeat.LanguageCommonLisp,
		"luau":                        heartbeat.LanguageLua,
		"m2":                          heartbeat.LanguageModula2,
		"make":                        heartbeat.LanguageMakefile,
		"mariadb":                     heartbeat.LanguageMySQL,
		"materialize":                 heartbeat.LanguageMaterializeSQLDialect,
		"mawk":                        heartbeat.LanguageAwk,
		"mcf":                         heartbeat.LanguageMCFunction,
		"md":                          heartbeat.LanguageMarkdown,
		"meson.build":                 heartbeat.LanguageMeson,
		"mf":                          heartbeat.LanguageMakefile,
		"mkd":                         heartbeat.LanguageMarkdown,
		"mma":                         heartbeat.LanguageMathematica,
		"moon":                        heartbeat.LanguageMoonScript,
		"morrowind":                   heartbeat.LanguageMorrowindScript,
		"mwscript":                    heartbeat.LanguageMorrowindScript,
		"mzn":                         heartbeat.LanguageMiniZinc,
		"MZN":                         heartbeat.LanguageMiniZinc,
		"mzql":                        heartbeat.LanguageMaterializeSQLDialect,
		"mzsql":                       heartbeat.LanguageMaterializeSQLDialect,
		"nawk":                        heartbeat.LanguageAwk,
		"nb":                          heartbeat.LanguageMathematica,
		"ng2":                         heartbeat.LanguageAngular2,
		"nim":                         heartbeat.LanguageNimrod,
		"Nim":                         heartbeat.LanguageNimrod,
		"nixos":                       heartbeat.LanguageNix,
		"no-highlight":                heartbeat.LanguageText,
		"nroff":                       heartbeat.LanguageGroff,
		"nsh":                         heartbeat.LanguageNSIS,
		"nsi":                         heartbeat.LanguageNSIS,
		"obj-c":                       heartbeat.LanguageObjectiveC,
		"objc":                        heartbeat.LanguageObjectiveC,
		"ones":                        heartbeat.LanguageOnesEnterprise,
		"openedge":                    heartbeat.LanguageOpenEdgeABL,
		"Org Mode":                    heartbeat.LanguageOrg,
		"orgmode":                     heartbeat.LanguageOrg,
		"php3":                        heartbeat.LanguagePHP,
		"php4":                        heartbeat.LanguagePHP,
		"php5":                        heartbeat.LanguagePHP,
		"pl":                          heartbeat.LanguagePerl,
		"pl6":                         heartbeat.LanguageRaku,
		"plain":                       heartbeat.LanguageText,
		"plaintext":                   heartbeat.LanguageText,
		"plc":                         heartbeat.LanguagePlutusCore,
		"posh":                        heartbeat.LanguagePowerShell,
		"postgres":                    heartbeat.LanguagePostgres,
		"postgresql":                  heartbeat.LanguagePostgres,
		"postscr":                     heartbeat.LanguagePostScript,
		"pov":                         heartbeat.LanguagePOVRay,
		"pq":                          heartbeat.LanguagePowerQuery,
		"progress":                    heartbeat.LanguageOpenEdgeABL,
		"properties":                  heartbeat.LanguageJavaProperties,
		"proto":                       heartbeat.LanguageProtocolBuffer,
		"protobuf":                    heartbeat.LanguageProtocolBuffer,
		"Protocol Buffer Text Format": heartbeat.LanguageProtocolBuffer,
		"ps1":                         heartbeat.LanguagePowerShell,
		"psd1":                        heartbeat.LanguagePowerShell,
		"PSL":                         heartbeat.LanguagePSL,
		"psl":                         heartbeat.LanguagePSL,
		"psm1":                        heartbeat.LanguagePowerShell,
		"pwsh":                        heartbeat.LanguagePowerShell,
		"py":                          heartbeat.LanguagePython,
		"py2":                         heartbeat.LanguagePython2,
		"py3":                         heartbeat.LanguagePython,
		"pyrex":                       heartbeat.LanguageCython,
		"python3":                     heartbeat.LanguagePython,
		"pyx":                         heartbeat.LanguageCython,
		"qbs":                         heartbeat.LanguageQML,
		"rb":                          heartbeat.LanguageRuby,
		"react":                       heartbeat.LanguageJSX,
		"ReasonML":                    heartbeat.LanguageReasonML,
		"reasonml":                    heartbeat.LanguageReasonML,
		"registry":                    heartbeat.LanguageRegistry,
		"rest":                        heartbeat.LanguageReStructuredText,
		"rgbasm":                      heartbeat.LanguageRGBDSAssembly,
		"rkt":                         heartbeat.LanguageRacket,
		"RPG IV":                      heartbeat.LanguageRPGLE,
		"rs":                          heartbeat.LanguageRust,
		"rst":                         heartbeat.LanguageReStructuredText,
		"SaltStack":                   heartbeat.LanguageSalt,
		"scm":                         heartbeat.LanguageScheme,
		"sh":                          heartbeat.LanguageBash,
		"sml":                         heartbeat.LanguageSML,
		"sol":                         heartbeat.LanguageSolidity,
		"sp":                          heartbeat.LanguageSourcePawn,
		"spec":                        heartbeat.LanguageRPMSpec,
		"spitfire":                    heartbeat.LanguageCheetah,
		"splus":                       heartbeat.LanguageR,
		"SQLRPGLE":                    heartbeat.LanguageRPGLE,
		"squeak":                      heartbeat.LanguageSmalltalk,
		"squid":                       heartbeat.LanguageSquidConf,
		"ssed":                        heartbeat.LanguageSed,
		"st":                          heartbeat.LanguageSmalltalk,
		"stas":                        heartbeat.LanguageStas,
		"sv":                          heartbeat.LanguageSystemVerilog,
		"Tal":                         heartbeat.LanguageUxntal,
		"tal":                         heartbeat.LanguageUxntal,
		"tape":                        heartbeat.LanguageVHS,
		"tf":                          heartbeat.LanguageTerraform,
		"Transact-SQL":                heartbeat.LanguageTransactSQL,
		"ts":                          heartbeat.LanguageTypeScript,
		"tv":                          heartbeat.LanguageTradingView,
		"TypoScriptCssData":           heartbeat.LanguageTypoScript,
		"typoscriptcssdata":           heartbeat.LanguageTypoScript,
		"TypoScriptHtmlData":          heartbeat.LanguageTypoScript,
		"typoscripthtmldata":          heartbeat.LanguageTypoScript,
		"udiff":                       heartbeat.LanguageDiff,
		"vapi":                        heartbeat.LanguageVala,
		"vim":                         heartbeat.LanguageVimL,
		"Visual Basic .NET":           heartbeat.LanguageVBNet,
		"vlang":                       heartbeat.LanguageV,
		"vsh":                         heartbeat.LanguageVShell,
		"vtt":                         heartbeat.LanguageWebVTT,
		"vue":                         heartbeat.LanguageVueJS,
		"WebAssembly Text Format":     heartbeat.LanguageWebAssembly,
		"wgsl":                        heartbeat.LanguageWebGPUShadingLanguage,
		"winbatch":                    heartbeat.LanguageBatchfile,
		"xml+genshi":                  heartbeat.LanguageGenshi,
		"xml+kid":                     heartbeat.LanguageGenshi,
		"xorg.conf":                   heartbeat.LanguageXorg,
		"z80":                         heartbeat.LanguageZ80Assembly,
		"zsh":                         heartbeat.LanguageBash,
		"🔥":                           heartbeat.LanguageMojo,
	}
}

func TestParseLanguage(t *testing.T) {
	// standard language names
	for value, language := range languageTests() {
		t.Run(value, func(t *testing.T) {
			parsed, ok := heartbeat.ParseLanguage(value)
			assert.True(t, ok)

			assert.Equal(t, language, parsed, fmt.Sprintf("got: %q, want: %q", parsed, language))
		})
	}

	// alias language names
	for value, language := range languageTestsAliases() {
		t.Run(value, func(t *testing.T) {
			parsed, ok := heartbeat.ParseLanguage(value)
			assert.True(t, ok)

			assert.Equal(t, language, parsed, fmt.Sprintf("got: %q, want: %q", parsed, language))
		})
	}

	t.Run("lower case", func(t *testing.T) {
		parsed, ok := heartbeat.ParseLanguage("go")
		assert.True(t, ok)

		assert.Equal(t, heartbeat.LanguageGo, parsed)
	})

	t.Run("hash", func(t *testing.T) {
		parsed, ok := heartbeat.ParseLanguage("CSharp")
		assert.True(t, ok)

		assert.Equal(t, heartbeat.LanguageCSharp, parsed)
	})

	t.Run("plus sign", func(t *testing.T) {
		parsed, ok := heartbeat.ParseLanguage("CPP")
		assert.True(t, ok)

		assert.Equal(t, heartbeat.LanguageCPP, parsed)
	})

	t.Run("leading space", func(t *testing.T) {
		parsed, ok := heartbeat.ParseLanguage(" Go")
		assert.True(t, ok)

		assert.Equal(t, heartbeat.LanguageGo, parsed)
	})

	t.Run("trailing space", func(t *testing.T) {
		parsed, ok := heartbeat.ParseLanguage("Go ")
		assert.True(t, ok)

		assert.Equal(t, heartbeat.LanguageGo, parsed)
	})

	t.Run("missing hyphen", func(t *testing.T) {
		parsed, ok := heartbeat.ParseLanguage("ObjectiveC")
		assert.True(t, ok)

		assert.Equal(t, heartbeat.LanguageObjectiveC, parsed)
	})

	t.Run("missing space", func(t *testing.T) {
		parsed, ok := heartbeat.ParseLanguage("Sublime Text Config")
		assert.True(t, ok)

		assert.Equal(t, heartbeat.LanguageSublimeTextConfig, parsed)
	})
}

func TestParseLanguage_Unknown(t *testing.T) {
	parsed, ok := heartbeat.ParseLanguage("invalid")

	assert.False(t, ok)
	assert.Equal(t, heartbeat.LanguageUnknown, parsed)
}

func TestParseLanguageFromChroma(t *testing.T) {
	tests := map[string]heartbeat.Language{
		"Ampl":               heartbeat.LanguageAMPL,
		"ApacheConf":         heartbeat.LanguageApacheConfig,
		"ArangoDB AQL":       heartbeat.LanguageArangoDBQueryLanguage,
		"c-objdump":          heartbeat.LanguageCObjdump,
		"Coldfusion CFC":     heartbeat.LanguageColdfusionCFC,
		"Coldfusion HTML":    heartbeat.LanguageColdfusionHTML,
		"cpp-objdump":        heartbeat.LanguageCppObjdump,
		"CUDA":               heartbeat.LanguageCUDA,
		"dns":                heartbeat.LanguageDNSZone,
		"EmacsLisp":          heartbeat.LanguageEmacsLisp,
		"FSharp":             heartbeat.LanguageFSharp,
		"GAS":                heartbeat.LanguageAssembly,
		"Go HTML Template":   heartbeat.LanguageGo,
		"Go Text Template":   heartbeat.LanguageGo,
		"Hxml":               heartbeat.LanguageHxml,
		"JSON-LD":            heartbeat.LanguageJSONLD,
		"ISCdhcpd":           heartbeat.LanguageISCdhcpd,
		"LessCss":            heartbeat.LanguageLess,
		"liquid":             heartbeat.LanguageLiquid,
		"markdown":           heartbeat.LanguageMarkdown,
		"NewLisp":            heartbeat.LanguageNewLisp,
		"Nim":                heartbeat.LanguageNimrod,
		"Ooc":                heartbeat.LanguageOoc,
		"Org Mode":           heartbeat.LanguageOrg,
		"plaintext":          heartbeat.LanguageText,
		"properties":         heartbeat.LanguageJavaProperties,
		"PSL":                heartbeat.LanguagePSL,
		"R":                  heartbeat.LanguageS,
		"react":              heartbeat.LanguageJSX,
		"ReasonML":           heartbeat.LanguageReasonML,
		"REBOL":              heartbeat.LanguageREBOL,
		"Rexx":               heartbeat.LanguageRexx,
		"Sed":                heartbeat.LanguageSed,
		"stas":               heartbeat.LanguageStas,
		"SYSTEMD":            heartbeat.LanguageSYSTEMD,
		"systemverilog":      heartbeat.LanguageSystemVerilog,
		"Tal":                heartbeat.LanguageUxntal,
		"Transact-SQL":       heartbeat.LanguageTransactSQL,
		"TypoScriptCssData":  heartbeat.LanguageTypoScript,
		"TypoScriptHtmlData": heartbeat.LanguageTypoScript,
		"VB.net":             heartbeat.LanguageVBNet,
		"verilog":            heartbeat.LanguageVerilog,
		"vue":                heartbeat.LanguageVueJS,
		"Web IDL":            heartbeat.LanguageWebIDL,
		// lowercase
		"zig": heartbeat.LanguageZig,
		// missing blank space
		"ProtocolBuffer": heartbeat.LanguageProtocolBuffer,
		// missing hyphen
		"ObjectiveC": heartbeat.LanguageObjectiveC,
		// plus sign
		"CPP": heartbeat.LanguageCPP,
		// hash
		"CSharp": heartbeat.LanguageCSharp,
	}

	for lexerName, language := range tests {
		t.Run(lexerName, func(t *testing.T) {
			parsed, ok := heartbeat.ParseLanguageFromChroma(lexerName)

			assert.True(t, ok)
			assert.Equal(t, language, parsed, fmt.Sprintf("got: %q, want: %q", parsed, language))
		})
	}
}

func TestParseLanguageFromChroma_Unknown(t *testing.T) {
	parsed, ok := heartbeat.ParseLanguageFromChroma("invalid")

	assert.False(t, ok)
	assert.Equal(t, heartbeat.LanguageUnknown, parsed)
}

func TestParseLanguageFromChroma_AllLexersSupported(t *testing.T) {
	for _, lexer := range lexers.GlobalLexerRegistry.Lexers {
		config := lexer.Config()

		parsed, ok := heartbeat.ParseLanguageFromChroma(config.Name)

		assert.True(t, ok, fmt.Sprintf("failed parsing language from lexer %q", config.Name))
		assert.NotEqual(t, heartbeat.LanguageUnknown, parsed, fmt.Sprintf(
			"parsed language.Unknown. Failed parsing language from lexer %q",
			config.Name,
		))
	}
}

func TestLanguage_String(t *testing.T) {
	for value, language := range languageTests() {
		t.Run(value, func(t *testing.T) {
			assert.Equal(t, value, language.String())
		})
	}
}

func TestLanguage_String_UnknownLanguage(t *testing.T) {
	var lang heartbeat.Language = -1
	assert.Equal(t, "Unknown", lang.String())
}

func TestLanguage_StringChroma(t *testing.T) {
	tests := map[string]heartbeat.Language{
		"Ampl":            heartbeat.LanguageAMPL,
		"ApacheConf":      heartbeat.LanguageApacheConfig,
		"ArangoDB AQL":    heartbeat.LanguageArangoDBQueryLanguage,
		"c-objdump":       heartbeat.LanguageCObjdump,
		"Coldfusion CFC":  heartbeat.LanguageColdfusionCFC,
		"Coldfusion HTML": heartbeat.LanguageColdfusionHTML,
		"cpp-objdump":     heartbeat.LanguageCppObjdump,
		"CUDA":            heartbeat.LanguageCUDA,
		"dns":             heartbeat.LanguageDNSZone,
		"EmacsLisp":       heartbeat.LanguageEmacsLisp,
		"GAS":             heartbeat.LanguageAssembly,
		"FSharp":          heartbeat.LanguageFSharp,
		"FStar":           heartbeat.LanguageFStar,
		"Go":              heartbeat.LanguageGo,
		"Hxml":            heartbeat.LanguageHxml,
		"ISCdhcpd":        heartbeat.LanguageISCdhcpd,
		"JSON-LD":         heartbeat.LanguageJSONLD,
		"LessCss":         heartbeat.LanguageLess,
		"liquid":          heartbeat.LanguageLiquid,
		"markdown":        heartbeat.LanguageMarkdown,
		"NewLisp":         heartbeat.LanguageNewLisp,
		"Nim":             heartbeat.LanguageNimrod,
		"Ooc":             heartbeat.LanguageOoc,
		"Org Mode":        heartbeat.LanguageOrg,
		"plaintext":       heartbeat.LanguageText,
		"properties":      heartbeat.LanguageJavaProperties,
		"PSL":             heartbeat.LanguagePSL,
		"R":               heartbeat.LanguageS,
		"react":           heartbeat.LanguageJSX,
		"ReasonML":        heartbeat.LanguageReasonML,
		"REBOL":           heartbeat.LanguageREBOL,
		"Rexx":            heartbeat.LanguageRexx,
		"Sed":             heartbeat.LanguageSed,
		"stas":            heartbeat.LanguageStas,
		"SYSTEMD":         heartbeat.LanguageSYSTEMD,
		"systemverilog":   heartbeat.LanguageSystemVerilog,
		"Tal":             heartbeat.LanguageUxntal,
		"Transact-SQL":    heartbeat.LanguageTransactSQL,
		"VB.net":          heartbeat.LanguageVBNet,
		"verilog":         heartbeat.LanguageVerilog,
		"vue":             heartbeat.LanguageVueJS,
		"Web IDL":         heartbeat.LanguageWebIDL,
	}

	for lexerName, language := range tests {
		t.Run(lexerName, func(t *testing.T) {
			assert.Equal(t, lexerName, language.StringChroma())
		})
	}
}

func TestLanguage_StringChroma_UnknownLanguage(t *testing.T) {
	var lang heartbeat.Language = -1
	assert.Equal(t, "Unknown", lang.StringChroma())
}

func TestLanguage_StringChroma_AllLexersSupported(t *testing.T) {
	for _, lexer := range lexers.GlobalLexerRegistry.Lexers {
		config := lexer.Config()

		// Aliases, which match in addition to standard spelling of languages are ignored here.
		// These are Chroma lexers that map to existing Language constants via chromaPriority.
		switch config.Name {
		case "Go HTML Template", "Go Text Template", "Go Template":
			continue
		case "TypoScriptCssData", "TypoScriptHtmlData":
			continue
		case "Protocol Buffer Text Format", "WebAssembly Text Format":
			continue
		case "ApacheConf", "ArangoDB AQL", "dns":
			continue
		}

		parsed, ok := heartbeat.ParseLanguageFromChroma(config.Name)
		require.True(t, ok, fmt.Sprintf("Failed parsing language from lexer %q", config.Name))
		require.NotEqual(t, heartbeat.LanguageUnknown, parsed, fmt.Sprintf(
			"Parsed language.Unknown. Failed parsing language from lexer %q",
			config.Name,
		))

		assert.Equal(t, config.Name, parsed.StringChroma())
	}
}

func BenchmarkParseLanguage(b *testing.B) {
	testCases := []string{
		"Go",
		"JavaScript",
		"Python",
		"TypeScript",
		"Rust",
		"unknown-language",
	}

	for b.Loop() {
		for _, tc := range testCases {
			heartbeat.ParseLanguage(tc)
		}
	}
}

func BenchmarkParseLanguage_Single(b *testing.B) {
	benchmarks := []struct {
		name  string
		input string
	}{
		{"common_language", "JavaScript"},
		{"case_insensitive", "PYTHON"},
		{"with_spaces", "Visual Basic"},
		{"unknown", "nonexistent-lang"},
	}

	for _, bm := range benchmarks {
		b.Run(bm.name, func(b *testing.B) {
			for i := 0; i < b.N; i++ {
				heartbeat.ParseLanguage(bm.input)
			}
		})
	}
}

func BenchmarkStringChroma(b *testing.B) {
	languages := []heartbeat.Language{
		heartbeat.LanguageGo,
		heartbeat.LanguageJavaScript,
		heartbeat.LanguagePython,
		heartbeat.LanguageAMPL,          // has chroma mapping
		heartbeat.LanguageFStar,         // has chroma mapping
		heartbeat.LanguageSystemVerilog, // has chroma mapping
	}

	for b.Loop() {
		for _, lang := range languages {
			lang.StringChroma()
		}
	}
}

func BenchmarkStringChroma_Single(b *testing.B) {
	benchmarks := []struct {
		name string
		lang heartbeat.Language
	}{
		{"with_chroma_mapping", heartbeat.LanguageAMPL},
		{"without_chroma_mapping", heartbeat.LanguageGo},
		{"fallback_to_string", heartbeat.LanguageJavaScript},
	}

	for _, bm := range benchmarks {
		b.Run(bm.name, func(b *testing.B) {
			for i := 0; i < b.N; i++ {
				bm.lang.StringChroma()
			}
		})
	}
}
