package lexer_test

import (
	"testing"

	"github.com/wakatime/wakatime-cli/pkg/heartbeat"

	"github.com/alecthomas/chroma/v2/lexers"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestChromaLanguagesRegister(t *testing.T) {
	tests := map[string]heartbeat.Language{
		"actionscript 3":                heartbeat.LanguageActionScript3,
		"adl":                           heartbeat.LanguageADL,
		"agda":                          heartbeat.LanguageAgda,
		"aheui":                         heartbeat.LanguageAheui,
		"alloy":                         heartbeat.LanguageAlloy,
		"ambienttalk":                   heartbeat.LanguageAmbientTalk,
		"ampl":                          heartbeat.LanguageAMPL,
		"arrow":                         heartbeat.LanguageArrow,
		"aspectj":                       heartbeat.LanguageAspectJ,
		"aspx-cs":                       heartbeat.LanguageAspxCSharp,
		"aspx-vb":                       heartbeat.LanguageAspxVBNet,
		"asymptote":                     heartbeat.LanguageAsymptote,
		"augeas":                        heartbeat.LanguageAugeas,
		"bare":                          heartbeat.LanguageBARE,
		"bbc basic":                     heartbeat.LanguageBBCBasic,
		"bbcode":                        heartbeat.LanguageBBCode,
		"bc":                            heartbeat.LanguageBC,
		"befunge":                       heartbeat.LanguageBefunge,
		"blazor":                        heartbeat.LanguageBlazor,
		"blitzmax":                      heartbeat.LanguageBlitzMax,
		"boa":                           heartbeat.LanguageBoa,
		"boo":                           heartbeat.LanguageBoo,
		"boogie":                        heartbeat.LanguageBoogie,
		"brainfuck":                     heartbeat.LanguageBrainfuck,
		"bst":                           heartbeat.LanguageBST,
		"bugs":                          heartbeat.LanguageBUGS,
		"c-objdump":                     heartbeat.LanguageCObjdump,
		"ca65 assembler":                heartbeat.LanguageCa65Assembler,
		"cadl":                          heartbeat.LanguageCADL,
		"camkes":                        heartbeat.LanguageCAmkES,
		"capdl":                         heartbeat.LanguageCapDL,
		"cbm basic v2":                  heartbeat.LanguageCBMBasicV2,
		"charmci":                       heartbeat.LanguageCharmci,
		"cirru":                         heartbeat.LanguageCirru,
		"clay":                          heartbeat.LanguageClay,
		"clean":                         heartbeat.LanguageClean,
		"clojurescript":                 heartbeat.LanguageClojureScript,
		"cobolfree":                     heartbeat.LanguageCOBOLFree,
		"coldfusion cfc":                heartbeat.LanguageColdfusionCFC,
		"coldfusion html":               heartbeat.LanguageColdfusionHTML,
		"component pascal":              heartbeat.LanguageComponentPascal,
		"coq":                           heartbeat.LanguageCoq,
		"cpp-objdump":                   heartbeat.LanguageCppObjdump,
		"cpsa":                          heartbeat.LanguageCPSA,
		"crmsh":                         heartbeat.LanguageCrmsh,
		"croc":                          heartbeat.LanguageCroc,
		"crontab":                       heartbeat.LanguageCrontab,
		"cryptol":                       heartbeat.LanguageCryptol,
		"csound document":               heartbeat.LanguageCsoundDocument,
		"csound orchestra":              heartbeat.LanguageCsoundOrchestra,
		"csound score":                  heartbeat.LanguageCsoundScore,
		"cuda":                          heartbeat.LanguageCUDA,
		"cypher":                        heartbeat.LanguageCypher,
		"d-objdump":                     heartbeat.LanguageDObjdump,
		"darcs patch":                   heartbeat.LanguageDarcsPatch,
		"dasm16":                        heartbeat.LanguageDASM16,
		"debian control file":           heartbeat.LanguageDebianControlFile,
		"debian sourcelist":             heartbeat.LanguageSourcesList,
		"delphi":                        heartbeat.LanguageDelphi,
		"devicetree":                    heartbeat.LanguageDevicetree,
		"dg":                            heartbeat.LanguageDG,
		"duel":                          heartbeat.LanguageDuel,
		"dylan session":                 heartbeat.LanguageDylanSession,
		"dylanlid":                      heartbeat.LanguageDylanLID,
		"e-mail":                        heartbeat.LanguageEMail,
		"earl grey":                     heartbeat.LanguageEarlGrey,
		"easytrieve":                    heartbeat.LanguageEasytrieve,
		"ec":                            heartbeat.LanguageEC,
		"ecl":                           heartbeat.LanguageECL,
		"eiffel":                        heartbeat.LanguageEiffel,
		"elixir iex session":            heartbeat.LanguageElixirIexSession,
		"embedded ragel":                heartbeat.LanguageRagelEmbedded,
		"erb":                           heartbeat.LanguageERB,
		"erlang erl session":            heartbeat.LanguageErlangErlSession,
		"evoque":                        heartbeat.LanguageEvoque,
		"execline":                      heartbeat.LanguageExecline,
		"ezhil":                         heartbeat.LanguageEzhil,
		"fancy":                         heartbeat.LanguageFancy,
		"fantom":                        heartbeat.LanguageFantom,
		"felix":                         heartbeat.LanguageFelix,
		"flatline":                      heartbeat.LanguageFlatline,
		"floscript":                     heartbeat.LanguageFloScript,
		"forth":                         heartbeat.LanguageForth,
		"foxpro":                        heartbeat.LanguageFoxPro,
		"freefem":                       heartbeat.LanguageFreefem,
		"fsharp":                        heartbeat.LanguageFSharp,
		"fstar":                         heartbeat.LanguageFStar,
		"gap":                           heartbeat.LanguageGap,
		"gas":                           heartbeat.LanguageGas,
		"gdscript":                      heartbeat.LanguageGDScript,
		"gettext catalog":               heartbeat.LanguageGettextCatalog,
		"golo":                          heartbeat.LanguageGolo,
		"gooddata-cl":                   heartbeat.LanguageGoodDataCL,
		"gosu":                          heartbeat.LanguageGosu,
		"gosu template":                 heartbeat.LanguageGosuTemplate,
		"groff":                         heartbeat.LanguageGroff,
		"haml":                          heartbeat.LanguageHaml,
		"hsail":                         heartbeat.LanguageHSAIL,
		"hspec":                         heartbeat.LanguageHspec,
		"html":                          heartbeat.LanguageHTML,
		"http":                          heartbeat.LanguageHTTP,
		"hxml":                          heartbeat.LanguageHxml,
		"hy":                            heartbeat.LanguageHy,
		"hybris":                        heartbeat.LanguageHybris,
		"icon":                          heartbeat.LanguageIcon,
		"idl":                           heartbeat.LanguageIDL,
		"inform 6":                      heartbeat.LanguageInform6,
		"inform 6 template":             heartbeat.LanguageInform6Template,
		"inform 7":                      heartbeat.LanguageInform7,
		"ini":                           heartbeat.LanguageINI,
		"ioke":                          heartbeat.LanguageIoke,
		"irc logs":                      heartbeat.LanguageIRCLogs,
		"isabelle":                      heartbeat.LanguageIsabelle,
		"jags":                          heartbeat.LanguageJAGS,
		"jasmin":                        heartbeat.LanguageJasmin,
		"java server page":              heartbeat.LanguageJSP,
		"jcl":                           heartbeat.LanguageJCL,
		"jsgf":                          heartbeat.LanguageJSGF,
		"json-ld":                       heartbeat.LanguageJSONLD,
		"julia console":                 heartbeat.LanguageJuliaConsole,
		"juttle":                        heartbeat.LanguageJuttle,
		"kal":                           heartbeat.LanguageKal,
		"kconfig":                       heartbeat.LanguageKconfig,
		"kernel log":                    heartbeat.LanguageKernelLog,
		"koka":                          heartbeat.LanguageKoka,
		"lasso":                         heartbeat.LanguageLasso,
		"lean":                          heartbeat.LanguageLean,
		"lesscss":                       heartbeat.LanguageLess,
		"limbo":                         heartbeat.LanguageLimbo,
		"liquid":                        heartbeat.LanguageLiquid,
		"literate agda":                 heartbeat.LanguageLiterateAgda,
		"literate cryptol":              heartbeat.LanguageLiterateCryptol,
		"literate haskell":              heartbeat.LanguageLiterateHaskell,
		"literate idris":                heartbeat.LanguageLiterateIdris,
		"livescript":                    heartbeat.LanguageLiveScript,
		"llvm-mir":                      heartbeat.LanguageLLVMMIR,
		"llvm-mir body":                 heartbeat.LanguageLLVMMIRBody,
		"logos":                         heartbeat.LanguageLogos,
		"logtalk":                       heartbeat.LanguageLogtalk,
		"lsl":                           heartbeat.LanguageLSL,
		"makefile":                      heartbeat.LanguageMakefile,
		"maql":                          heartbeat.LanguageMAQL,
		"marko":                         heartbeat.LanguageMarko,
		"mask":                          heartbeat.LanguageMask,
		"matlab":                        heartbeat.LanguageMatlab,
		"matlab session":                heartbeat.LanguageMatlabSession,
		"mime":                          heartbeat.LanguageMIME,
		"minid":                         heartbeat.LanguageMiniD,
		"miniscript":                    heartbeat.LanguageMiniScript,
		"modelica":                      heartbeat.LanguageModelica,
		"modula-2":                      heartbeat.LanguageModula2,
		"monkey":                        heartbeat.LanguageMonkey,
		"monte":                         heartbeat.LanguageMonte,
		"moocode":                       heartbeat.LanguageMOOCode,
		"moonscript":                    heartbeat.LanguageMoonScript,
		"mosel":                         heartbeat.LanguageMosel,
		"mozhashpreproc":                heartbeat.LanguageMozPreprocHash,
		"mozpercentpreproc":             heartbeat.LanguageMozPreprocPercent,
		"mql":                           heartbeat.LanguageMQL,
		"mscgen":                        heartbeat.LanguageMscgen,
		"msdos session":                 heartbeat.LanguageMSDOSSession,
		"mupad":                         heartbeat.LanguageMuPAD,
		"mustache":                      heartbeat.LanguageMustache,
		"mxml":                          heartbeat.LanguageMXML,
		"nasm":                          heartbeat.LanguageNASM,
		"ncl":                           heartbeat.LanguageNCL,
		"nemerle":                       heartbeat.LanguageNemerle,
		"nesc":                          heartbeat.LanguageNesC,
		"newlisp":                       heartbeat.LanguageNewLisp,
		"nit":                           heartbeat.LanguageNit,
		"notmuch":                       heartbeat.LanguageNotmuch,
		"nsis":                          heartbeat.LanguageNSIS,
		"numpy":                         heartbeat.LanguageNumPy,
		"nusmv":                         heartbeat.LanguageNuSMV,
		"objdump":                       heartbeat.LanguageObjdump,
		"objdump-nasm":                  heartbeat.LanguageNASMObjdump,
		"objective-c":                   heartbeat.LanguageObjectiveC,
		"objective-c++":                 heartbeat.LanguageObjectiveCPP,
		"objective-j":                   heartbeat.LanguageObjectiveJ,
		"ooc":                           heartbeat.LanguageOoc,
		"opa":                           heartbeat.LanguageOpa,
		"openedge abl":                  heartbeat.LanguageOpenEdgeABL,
		"pan":                           heartbeat.LanguagePan,
		"parasail":                      heartbeat.LanguageParaSail,
		"pawn":                          heartbeat.LanguagePawn,
		"peg":                           heartbeat.LanguagePEG,
		"perl":                          heartbeat.LanguagePerl,
		"perl6":                         heartbeat.LanguagePerl6,
		"pike":                          heartbeat.LanguagePike,
		"pointless":                     heartbeat.LanguagePointless,
		"postgresql console (psql)":     heartbeat.LanguagePostgresConsole,
		"povray":                        heartbeat.LanguagePOVRay,
		"powershell session":            heartbeat.LanguagePowerShellSession,
		"praat":                         heartbeat.LanguagePraat,
		"processing":                    heartbeat.LanguageProcessing,
		"prolog":                        heartbeat.LanguageProlog,
		"psysh console session for php": heartbeat.LanguagePsyShPHP,
		"pug":                           heartbeat.LanguagePug,
		"pypy log":                      heartbeat.LanguagePyPyLog,
		"python":                        heartbeat.LanguagePython,
		"python 2":                      heartbeat.LanguagePython2,
		"python 2.x traceback":          heartbeat.LanguagePython2Traceback,
		"python console session":        heartbeat.LanguagePythonConsole,
		"python traceback":              heartbeat.LanguagePythonTraceback,
		"qbasic":                        heartbeat.LanguageQBasic,
		"qvto":                          heartbeat.LanguageQVTO,
		"r":                             heartbeat.LanguageR,
		"raw token data":                heartbeat.LanguageRawToken,
		"razor":                         heartbeat.LanguageRazor,
		"rconsole":                      heartbeat.LanguageRConsole,
		"rd":                            heartbeat.LanguageRd,
		"rebol":                         heartbeat.LanguageREBOL,
		"red":                           heartbeat.LanguageRed,
		"redcode":                       heartbeat.LanguageRedcode,
		"relax-ng compact":              heartbeat.LanguageRNGCompact,
		"rescript":                      heartbeat.LanguageReScript,
		"resourcebundle":                heartbeat.LanguageResourceBundle,
		"rhtml":                         heartbeat.LanguageRHTML,
		"ride":                          heartbeat.LanguageRide,
		"roboconf graph":                heartbeat.LanguageRoboconfGraph,
		"roboconf instances":            heartbeat.LanguageRoboconfInstances,
		"robotframework":                heartbeat.LanguageRobotFramework,
		"rpmspec":                       heartbeat.LanguageRPMSpec,
		"rql":                           heartbeat.LanguageRQL,
		"rsl":                           heartbeat.LanguageRSL,
		"ruby irb session":              heartbeat.LanguageRubyIRBSession,
		"sarl":                          heartbeat.LanguageSARL,
		"scalate server page":           heartbeat.LanguageSSP,
		"scaml":                         heartbeat.LanguageScaml,
		"scdoc":                         heartbeat.LanguageScdoc,
		"shen":                          heartbeat.LanguageShen,
		"shexc":                         heartbeat.LanguageShExC,
		"silver":                        heartbeat.LanguageSilver,
		"singularity":                   heartbeat.LanguageSingularity,
		"sketch drawing":                heartbeat.LanguageSketchDrawing,
		"slash":                         heartbeat.LanguageSlash,
		"slim":                          heartbeat.LanguageSlim,
		"slint":                         heartbeat.LanguageSlint,
		"slurm":                         heartbeat.LanguageSlurm,
		"smali":                         heartbeat.LanguageSmali,
		"smartgameformat":               heartbeat.LanguageSmartGameFormat,
		"snowball":                      heartbeat.LanguageSnowball,
		"sqlite3con":                    heartbeat.LanguageSqlite3con,
		"stan":                          heartbeat.LanguageStan,
		"stata":                         heartbeat.LanguageStata,
		"sublime text config":           heartbeat.LanguageSublimeTextConfig,
		"supercollider":                 heartbeat.LanguageSuperCollider,
		"swig":                          heartbeat.LanguageSWIG,
		"tads 3":                        heartbeat.LanguageTADS3,
		"tap":                           heartbeat.LanguageTAP,
		"tasm":                          heartbeat.LanguageTASM,
		"tcsh session":                  heartbeat.LanguageTcshSession,
		"tea":                           heartbeat.LanguageTea,
		"tera term macro":               heartbeat.LanguageTeraTerm,
		"tiddler":                       heartbeat.LanguageTiddler,
		"todotxt":                       heartbeat.LanguageTodotxt,
		"trafficscript":                 heartbeat.LanguageTrafficScript,
		"transact-sql":                  heartbeat.LanguageTransactSQL,
		"treetop":                       heartbeat.LanguageTreetop,
		"turtle":                        heartbeat.LanguageTurtle,
		"typographic number theory":     heartbeat.LanguageTNT,
		"ucode":                         heartbeat.LanguageUcode,
		"unicon":                        heartbeat.LanguageUnicon,
		"urbiscript":                    heartbeat.LanguageUrbiScript,
		"usd":                           heartbeat.LanguageUSD,
		"vb.net":                        heartbeat.LanguageVBNet,
		"vbscript":                      heartbeat.LanguageVBScript,
		"vcl":                           heartbeat.LanguageVCL,
		"vclsnippets":                   heartbeat.LanguageVCLSnippets,
		"vctreestatus":                  heartbeat.LanguageVCTreeStatus,
		"velocity":                      heartbeat.LanguageVelocity,
		"verilog":                       heartbeat.LanguageVerilog,
		"vgl":                           heartbeat.LanguageVGL,
		"wdiff":                         heartbeat.LanguageWDiff,
		"web idl":                       heartbeat.LanguageWebIDL,
		"x10":                           heartbeat.LanguageX10,
		"xaml":                          heartbeat.LanguageXAML,
		"xml":                           heartbeat.LanguageXML,
		"xquery":                        heartbeat.LanguageXQuery,
		"xslt":                          heartbeat.LanguageXSLT,
		"xtend":                         heartbeat.LanguageXtend,
		"xtlang":                        heartbeat.LanguageXtlang,
		"zeek":                          heartbeat.LanguageZeek,
		"zephir":                        heartbeat.LanguageZephir,
	}

	for name, test := range tests {
		t.Run(name, func(t *testing.T) {
			language := test.StringChroma()
			require.NotEqual(t, heartbeat.LanguageUnknown.String(), language)

			lexer := lexers.Get(language)
			if lexer != nil {
				// assert lexer is registered but analyser don't
				assert.Nil(t, lexer.Config().Analyse)
			}
		})
	}
}
