on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@master
      - uses: actions/setup-go@v2
        with:
          go-version: "1.14"
      - name: "Install linter"
        run: go get -u golang.org/x/lint/golint
      - name: "Pull dependencies"
        run: go mod vendor
      - name: "Unit tests"
        run: go test -v ./...
      - name: "Linter"
        run: golint lib/...
