on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@master
      - uses: actions/setup-go@v1
        with:
          go-version: "1.13.3"
      - name: "Pull dependencies"
        run: go mod vendor
      - name: "Unit tests"
        run: go test -v ./...
