on:
  push:
    branches:
      - 'refs/heads/develop'
      - 'refs/heads/master'
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: jungwinter/split@v1
        id: split
        with:
          seperator: "/"
          msg: ${{ GITHUB_REF }}
      - name: "Publish new release"
        env:
          GORELEASER_CURRENT_TAG: ${{ steps.split.outputs._2 }}
        run: >-
          docker run --privileged --rm
          -e GO_VERSION=${{ env.GO_VERSION }}
          -e GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          -v $PWD:/go/src/github.com/wakatime/wakatime-cli
          -v /var/run/docker.sock:/var/run/docker.sock
          -w /go/src/github.com/wakatime/wakatime-cli
          mailchain/goreleaser-xcgo --rm-dist
