on:
  push:
    branches:
      - "develop"
      - "master"

env:
  GO_VERSION: "1.15"

jobs:
  # test:
  #   name: Test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: "Checkout"
  #       uses: actions/checkout@v2
  #     - uses: actions/setup-go@v2
  #       with:
  #         go-version: ${{ env.GO_VERSION }}
  #     - name: "Pull dependencies"
  #       run: go mod vendor
  #     - name: "Unit tests"
  #       run: make test
  #     - name: "Linter"
  #       run: make lint
  
  # test-windows:
  #   name: Test Windows
  #   runs-on: windows-latest
  #   steps:
  #     - name: "Checkout"
  #       uses: actions/checkout@v2
  #     - uses: actions/setup-go@v2
  #       with:
  #         go-version: ${{ env.GO_VERSION }}
  #     - name: "Pull dependencies"
  #       run: go mod vendor
  #     - name: "Unit tests"
  #       run: make test
  #     - name: "Linter"
  #       run: make lint
  
  tag:
    name: Tag
    runs-on: ubuntu-latest
    # needs: [test, test-windows]
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: "Create semver tag"
        id: semver-tag
        uses: gandarez/semver-action@v1.0.1
        with:
          prerelease_id: "alpha"
          debug: "true"
      - name: "Created tag"
        run: echo "tag ${{ steps.semver-tag.outputs.semver_tag }}"
  
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [tag]
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: jungwinter/split@v1
        id: split
        with:
          seperator: "/"
          msg: $GITHUB_REF
      - name: "Publish new release"
        env:
          GORELEASER_CURRENT_TAG: ${{ steps.split.outputs._2 }}
        run: >-
          docker run --privileged --rm
          -e GO_VERSION=${{ env.GO_VERSION }}
          -e GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          -v $PWD:/go/src/github.com/wakatime/wakatime-cli
          -v /var/run/docker.sock:/var/run/docker.sock
          -w /go/src/github.com/wakatime/wakatime-cli
          mailchain/goreleaser-xcgo --rm-dist
