on:
  push:
    branches-ignore:
      - "develop"
      - "master"

env:
  GO_VERSION: "1.15"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: "Pull dependencies"
        run: go mod vendor
      - name: "Unit tests"
        run: make test
      - name: "Linter"
        run: make lint
  
  test-windows:
    name: Test Windows
    runs-on: windows-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: "Pull dependencies"
        run: go mod vendor
      - name: "Unit tests"
        run: make test
      - name: "Linter"
        run: make lint
