on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: "Publish new release"
        run: >-
          docker run --privileged --rm
          -e GO_VERSION=${{ env.GO_VERSION }}
          -e GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          -v $PWD:/go/src/github.com/wakatime/wakatime-cli
          -v /var/run/docker.sock:/var/run/docker.sock
          -w /go/src/github.com/wakatime/wakatime-cli
          mailchain/goreleaser-xcgo --rm-dist
